/**
 * Multilingual hazard / conflict terms for wiki_top matching.
 * Every term is an AI draft. Do not treat as a verified glossary.
 * Status: ai_seed_unverified
 */
export const HAZARD_TERM_STATUS = 'ai_seed_unverified' as const

export const HAZARD_CONCEPTS = [
  'flood',
  'landslide',
  'cholera',
  'outbreak',
  'earthquake',
  'cyclone',
  'evacuation',
  'mobilization',
  'curfew',
  'coup',
  'airstrike',
  'dam',
  'drought',
  'famine',
  'plague',
  'radiation',
  'refugee',
] as const

export type HazardConcept = (typeof HAZARD_CONCEPTS)[number]

export interface HazardTerm {
  lang: string
  concept: HazardConcept
  term: string
  status: typeof HAZARD_TERM_STATUS
}

const RAW: Record<string, Partial<Record<HazardConcept, string[]>>> = {
  en: {
    flood: ['flood', 'flooding'],
    landslide: ['landslide', 'mudslide'],
    cholera: ['cholera'],
    outbreak: ['outbreak', 'epidemic'],
    earthquake: ['earthquake', 'quake'],
    cyclone: ['cyclone', 'hurricane', 'typhoon'],
    evacuation: ['evacuation', 'evacuate'],
    mobilization: ['mobilization', 'mobilisation'],
    curfew: ['curfew'],
    coup: ['coup'],
    airstrike: ['airstrike', 'air strike'],
    dam: ['dam collapse', 'dam breach'],
    drought: ['drought'],
    famine: ['famine'],
    plague: ['plague'],
    radiation: ['radiation', 'nuclear leak'],
    refugee: ['refugee'],
  },
  ar: {
    flood: ['فيضان', 'سيول'],
    landslide: ['انهيار أرضي'],
    cholera: ['كوليرا'],
    outbreak: ['تفشي', 'وباء'],
    earthquake: ['زلزال'],
    cyclone: ['إعصار'],
    evacuation: ['إخلاء'],
    mobilization: ['تعبئة'],
    curfew: ['حظر تجول'],
    coup: ['انقلاب'],
    airstrike: ['غارة جوية'],
    dam: ['سد'],
    drought: ['جفاف'],
    famine: ['مجاعة'],
    plague: ['طاعون'],
    radiation: ['إشعاع'],
    refugee: ['لاجئ', 'لاجئين'],
  },
  fa: {
    flood: ['سیل'],
    landslide: ['زمین‌لغزش'],
    cholera: ['وبا'],
    outbreak: ['شیوع'],
    earthquake: ['زمین‌لرزه', 'زلزله'],
    cyclone: ['طوفان'],
    evacuation: ['تخلیه'],
    mobilization: ['بسیج'],
    curfew: ['منع آمد و شد'],
    coup: ['کودتا'],
    airstrike: ['حمله هوایی'],
    dam: ['سد'],
    drought: ['خشکسالی'],
    famine: ['قحطی'],
    plague: ['طاعون'],
    radiation: ['تشعشع'],
    refugee: ['پناهنده'],
  },
  uk: {
    flood: ['повінь'],
    landslide: ['зсув'],
    cholera: ['холера'],
    outbreak: ['спалах'],
    earthquake: ['землетрус'],
    cyclone: ['циклон'],
    evacuation: ['евакуація'],
    mobilization: ['мобілізація'],
    curfew: ['комендантська година'],
    coup: ['переворот'],
    airstrike: ['авіаудар'],
    dam: ['гребля'],
    drought: ['посуха'],
    famine: ['голод'],
    plague: ['чума'],
    radiation: ['радіація'],
    refugee: ['біженець', 'біженці'],
  },
  ru: {
    flood: ['наводнение', 'паводок'],
    landslide: ['оползень'],
    cholera: ['холера'],
    outbreak: ['вспышка'],
    earthquake: ['землетрясение'],
    cyclone: ['циклон'],
    evacuation: ['эвакуация'],
    mobilization: ['мобилизация'],
    curfew: ['комендантский час'],
    coup: ['переворот'],
    airstrike: ['авиаудар'],
    dam: ['плотина'],
    drought: ['засуха'],
    famine: ['голод'],
    plague: ['чума'],
    radiation: ['радиация'],
    refugee: ['беженец', 'беженцы'],
  },
  ne: {
    flood: ['बाढी'],
    landslide: ['पहिरो'],
    cholera: ['हैजा'],
    outbreak: ['प्रकोप'],
    earthquake: ['भूकम्प'],
    cyclone: ['चक्रवात'],
    evacuation: ['खाली'],
    mobilization: ['परिचालन'],
    curfew: ['कर्फ्यू'],
    coup: ['कू'],
    airstrike: ['हवाई आक्रमण'],
    dam: ['बाँध'],
    drought: ['खडेरी'],
    famine: ['अकाल'],
    plague: ['प्लेग'],
    radiation: ['विकिरण'],
    refugee: ['शरणार्थी'],
  },
  bn: {
    flood: ['বন্যা'],
    landslide: ['ভূমিধস'],
    cholera: ['কলেরা'],
    outbreak: ['প্রাদুর্ভাব'],
    earthquake: ['ভূমিকম্প'],
    cyclone: ['ঘূর্ণিঝড়'],
    evacuation: ['সরিয়ে'],
    mobilization: ['সমাবেশ'],
    curfew: ['কারফিউ'],
    coup: ['অভ্যুত্থান'],
    airstrike: ['বিমান হামলা'],
    dam: ['বাঁধ'],
    drought: ['খরা'],
    famine: ['দুর্ভিক্ষ'],
    plague: ['প্লেগ'],
    radiation: ['বিকিরণ'],
    refugee: ['শরণার্থী'],
  },
  hi: {
    flood: ['बाढ़'],
    landslide: ['भूस्खलन'],
    cholera: ['हैजा'],
    outbreak: ['प्रकोप'],
    earthquake: ['भूकंप'],
    cyclone: ['चक्रवात'],
    evacuation: ['निकासी'],
    mobilization: ['Mobilization', 'लामबंदी'],
    curfew: ['कर्फ्यू'],
    coup: ['तख्तापलट'],
    airstrike: ['हवाई हमला'],
    dam: ['बाँध'],
    drought: ['सूखा'],
    famine: ['अकाल'],
    plague: ['प्लेग'],
    radiation: ['विकिरण'],
    refugee: ['शरणार्थी'],
  },
  ur: {
    flood: ['سیلاب'],
    landslide: ['زمین کھسکنا'],
    cholera: ['ہیضہ'],
    outbreak: ['وباء'],
    earthquake: ['زلزلہ'],
    cyclone: ['طوفان'],
    evacuation: ['انخلاء'],
    mobilization: ['mobilization'],
    curfew: ['کرفیو'],
    coup: ['انقلاب'],
    airstrike: ['ہوائی حملہ'],
    dam: ['بند'],
    drought: ['خشک سالی'],
    famine: ['قحط'],
    plague: ['طاعون'],
    radiation: ['شعاع'],
    refugee: ['مہاجر'],
  },
  ps: {
    flood: ['سيلاب'],
    landslide: ['ځمکښوېدنه'],
    cholera: ['کولرا'],
    outbreak: ['خپرېدنه'],
    earthquake: ['زلزله'],
    cyclone: ['طوفان'],
    evacuation: ['تشول'],
    mobilization: ['mobilization'],
    curfew: ['کرفيو'],
    coup: ['کودتا'],
    airstrike: ['هوايي بريد'],
    dam: ['بند'],
    drought: ['وچکالي'],
    famine: ['قحط'],
    plague: ['طاعون'],
    radiation: ['وړانګه'],
    refugee: ['کډوال'],
  },
  my: {
    flood: ['ရေကြီး'],
    landslide: ['မြေပြို'],
    cholera: ['ကာလဝမ်း'],
    outbreak: ['ကူးစက်'],
    earthquake: ['ငလျင်'],
    cyclone: ['ဆိုင်ကလုန်း'],
    evacuation: ['ရွှေ့ပြောင်း'],
    mobilization: ['mobilization'],
    curfew: ['ညမထွက်ရ'],
    coup: ['အာဏာသိမ်း'],
    airstrike: ['လေကြောင်းတိုက်ခိုက်'],
    dam: ['ဆည်'],
    drought: ['မိုးခေါင်'],
    famine: ['အငတ်ဘေး'],
    plague: ['ပလိပ်'],
    radiation: ['ရောင်ခြည်'],
    refugee: ['ဒုက္ခသည်'],
  },
  th: {
    flood: ['น้ำท่วม'],
    landslide: ['ดินถล่ม'],
    cholera: ['อหิวาต์'],
    outbreak: ['การระบาด'],
    earthquake: ['แผ่นดินไหว'],
    cyclone: ['พายุไซโคลน'],
    evacuation: ['อพยพ'],
    mobilization: ['ระดม'],
    curfew: ['เคอร์ฟิว'],
    coup: ['รัฐประหาร'],
    airstrike: ['โจมตีทางอากาศ'],
    dam: ['เขื่อน'],
    drought: ['ภัยแล้ง'],
    famine: ['ทุพภิกขภัย'],
    plague: ['กาฬโรค'],
    radiation: ['รังสี'],
    refugee: ['ผู้ลี้ภัย'],
  },
  vi: {
    flood: ['lũ lụt', 'ngập lụt'],
    landslide: ['sạt lở'],
    cholera: ['tả'],
    outbreak: ['bùng phát'],
    earthquake: ['động đất'],
    cyclone: ['bão'],
    evacuation: ['sơ tán'],
    mobilization: ['huy động'],
    curfew: ['giới nghiêm'],
    coup: ['đảo chính'],
    airstrike: ['không kích'],
    dam: ['đập'],
    drought: ['hạn hán'],
    famine: ['nạn đói'],
    plague: ['dịch hạch'],
    radiation: ['phóng xạ'],
    refugee: ['người tị nạn'],
  },
  id: {
    flood: ['banjir'],
    landslide: ['tanah longsor'],
    cholera: ['kolera'],
    outbreak: ['wabah'],
    earthquake: ['gempa'],
    cyclone: ['siklon'],
    evacuation: ['evakuasi'],
    mobilization: ['mobilisasi'],
    curfew: ['jam malam'],
    coup: ['kudeta'],
    airstrike: ['serangan udara'],
    dam: ['bendungan'],
    drought: ['kekeringan'],
    famine: ['kelaparan'],
    plague: ['sampar'],
    radiation: ['radiasi'],
    refugee: ['pengungsi'],
  },
  tl: {
    flood: ['baha'],
    landslide: ['guho'],
    cholera: ['kolera'],
    outbreak: ['outbreak'],
    earthquake: ['lindol'],
    cyclone: ['bagyo'],
    evacuation: ['likas'],
    mobilization: ['mobilisasyon'],
    curfew: ['curfew'],
    coup: ['coup'],
    airstrike: ['airstrike'],
    dam: ['dike'],
    drought: ['tagtuyot'],
    famine: ['taggutom'],
    plague: ['plague'],
    radiation: ['radyasyon'],
    refugee: ['refugee'],
  },
  sw: {
    flood: ['mafuriko'],
    landslide: ['maporomoko'],
    cholera: ['kipindupindu'],
    outbreak: ['mlipuko'],
    earthquake: ['tetemeko'],
    cyclone: ['kimbunga'],
    evacuation: ['kuhamisha'],
    mobilization: ['kuhamasisha'],
    curfew: ['curfew'],
    coup: ['mapinduzi'],
    airstrike: ['shambulio la anga'],
    dam: ['bwawa'],
    drought: ['ukame'],
    famine: ['njaa'],
    plague: ['tauni'],
    radiation: ['mionzi'],
    refugee: ['mkimbizi'],
  },
  am: {
    flood: ['ጮርፍ'],
    landslide: ['የመሬት መንሸራተት'],
    cholera: ['ኮሌራ'],
    outbreak: ['ወረርሽኝ'],
    earthquake: ['መሬት መንቀጥቀጥ'],
    cyclone: ['አውሎ ነፋስ'],
    evacuation: ['መልቀቅ'],
    mobilization: ['ማሰባሰብ'],
    curfew: ['እንቅስቃሴ ማገድ'],
    coup: ['መፈንቅለ መንግስት'],
    airstrike: ['የአየር ጥቃት'],
    dam: ['ግድብ'],
    drought: ['ድርቅ'],
    famine: ['ረሃብ'],
    plague: ['ቸነፈር'],
    radiation: ['ጨረር'],
    refugee: ['ስደተኛ'],
  },
  so: {
    flood: ['daad'],
    landslide: ['dhul-gariir'],
    cholera: ['daacuun'],
    outbreak: ['faafid'],
    earthquake: ['dhulgariir'],
    cyclone: ['duufaan'],
    evacuation: ['daadgureyn'],
    mobilization: ['abaabul'],
    curfew: ['bandow'],
    coup: ['afgambi'],
    airstrike: ['duqeyn Cir'],
    dam: ['biyo-xireen'],
    drought: ['abaar'],
    famine: ['abaar macaluul'],
    plague: ['daacuun weyn'],
    radiation: ['shucaac'],
    refugee: ['qaxooti'],
  },
  ha: {
    flood: ['ambaliya'],
    landslide: ['rushewar ƙasa'],
    cholera: ['kwalara'],
    outbreak: ['annoba'],
    earthquake: ['girgizar ƙasa'],
    cyclone: ['guguwa'],
    evacuation: ['korewa'],
    mobilization: ['tara'],
    curfew: ['dokar hana fita'],
    coup: ['juyin mulki'],
    airstrike: ['harin jirgin sama'],
    dam: ['madatsar ruwa'],
    drought: ['fari'],
    famine: ['yunwa'],
    plague: ['annoba'],
    radiation: ['radiation'],
    refugee: ['gurguzu'],
  },
  yo: {
    flood: ['ìkún-omi'],
    landslide: ['ìjìnlẹ̀ ilẹ̀'],
    cholera: ['cholera'],
    outbreak: ['àjàkálẹ̀ àrùn'],
    earthquake: ['ìṣẹ̀lẹ̀ ilẹ̀'],
    cyclone: ['ìjì líle'],
    evacuation: ['ìkó kúrò'],
    mobilization: ['ìkójọpọ̀'],
    curfew: ['curfew'],
    coup: ['ìyípadà ìjọba'],
    airstrike: ['ìkọlù òfurufú'],
    dam: ['idídò'],
    drought: ['ògbélé'],
    famine: ['ìyàn'],
    plague: ['àjàkálẹ̀'],
    radiation: ['radiation'],
    refugee: ['asasala'],
  },
  fr: {
    flood: ['inondation'],
    landslide: ['glissement de terrain'],
    cholera: ['choléra'],
    outbreak: ['épidémie'],
    earthquake: ['tremblement de terre', 'séisme'],
    cyclone: ['cyclone'],
    evacuation: ['évacuation'],
    mobilization: ['mobilisation'],
    curfew: ['couvre-feu'],
    coup: ['coup d\'État', 'coup d\'etat'],
    airstrike: ['frappe aérienne'],
    dam: ['barrage'],
    drought: ['sécheresse'],
    famine: ['famine'],
    plague: ['peste'],
    radiation: ['radiation'],
    refugee: ['réfugié'],
  },
  es: {
    flood: ['inundación'],
    landslide: ['deslizamiento'],
    cholera: ['cólera'],
    outbreak: ['brote', 'epidemia'],
    earthquake: ['terremoto'],
    cyclone: ['ciclón', 'huracán'],
    evacuation: ['evacuación'],
    mobilization: ['movilización'],
    curfew: ['toque de queda'],
    coup: ['golpe de estado'],
    airstrike: ['ataque aéreo'],
    dam: ['represa', 'presa'],
    drought: ['sequía'],
    famine: ['hambruna'],
    plague: ['peste'],
    radiation: ['radiación'],
    refugee: ['refugiado'],
  },
  pt: {
    flood: ['inundação', 'enchente'],
    landslide: ['deslizamento'],
    cholera: ['cólera'],
    outbreak: ['surto'],
    earthquake: ['terremoto'],
    cyclone: ['ciclone'],
    evacuation: ['evacuação'],
    mobilization: ['mobilização'],
    curfew: ['toque de recolher'],
    coup: ['golpe'],
    airstrike: ['ataque aéreo'],
    dam: ['barragem'],
    drought: ['seca'],
    famine: ['fome'],
    plague: ['peste'],
    radiation: ['radiação'],
    refugee: ['refugiado'],
  },
  tr: {
    flood: ['sel'],
    landslide: ['heyelan'],
    cholera: ['kolera'],
    outbreak: ['salgın'],
    earthquake: ['deprem'],
    cyclone: ['siklon'],
    evacuation: ['tahliye'],
    mobilization: ['seferberlik'],
    curfew: ['sokağa çıkma yasağı'],
    coup: ['darbe'],
    airstrike: ['hava saldırısı'],
    dam: ['baraj'],
    drought: ['kuraklık'],
    famine: ['kıtlık'],
    plague: ['veba'],
    radiation: ['radyasyon'],
    refugee: ['mülteci'],
  },
  he: {
    flood: ['שיטפון'],
    landslide: ['מפולת'],
    cholera: ['כולרה'],
    outbreak: ['התפרצות'],
    earthquake: ['רעידת אדמה'],
    cyclone: ['ציקלון'],
    evacuation: ['פינוי'],
    mobilization: ['גיוס'],
    curfew: ['עוצר'],
    coup: ['הפיכה'],
    airstrike: ['תקיפה אווירית'],
    dam: ['סכר'],
    drought: ['בצורת'],
    famine: ['רעב'],
    plague: ['מגפה'],
    radiation: ['קרינה'],
    refugee: ['פליט'],
  },
  ko: {
    flood: ['홍수', '침수'],
    landslide: ['산사태'],
    cholera: ['콜레라'],
    outbreak: ['발병', '유행'],
    earthquake: ['지진'],
    cyclone: ['태풍', '사이클론'],
    evacuation: ['대피'],
    mobilization: ['동원'],
    curfew: ['통행금지'],
    coup: ['쿠데타'],
    airstrike: ['공습'],
    dam: ['댐'],
    drought: ['가뭄'],
    famine: ['기근'],
    plague: ['페스트'],
    radiation: ['방사선'],
    refugee: ['난민'],
  },
  ja: {
    flood: ['洪水', '浸水'],
    landslide: ['土砂崩れ', '地滑り'],
    cholera: ['コレラ'],
    outbreak: ['アウトブレイク', '流行'],
    earthquake: ['地震'],
    cyclone: ['台風', 'サイクロン'],
    evacuation: ['避難'],
    mobilization: ['動員'],
    curfew: ['外出禁止'],
    coup: ['クーデター'],
    airstrike: ['空爆'],
    dam: ['ダム決壊'],
    drought: ['干ばつ'],
    famine: ['飢饉'],
    plague: ['ペスト'],
    radiation: ['放射線'],
    refugee: ['難民'],
  },
  zh: {
    flood: ['洪水', '水灾'],
    landslide: ['滑坡', '山体滑坡'],
    cholera: ['霍乱'],
    outbreak: ['爆发', '疫情'],
    earthquake: ['地震'],
    cyclone: ['气旋', '台风'],
    evacuation: ['疏散', '撤离'],
    mobilization: ['动员'],
    curfew: ['宵禁'],
    coup: ['政变'],
    airstrike: ['空袭'],
    dam: ['溃坝', '大坝'],
    drought: ['干旱'],
    famine: ['饥荒'],
    plague: ['鼠疫'],
    radiation: ['辐射'],
    refugee: ['难民'],
  },
  ms: {
    flood: ['banjir'],
    landslide: ['tanah runtuh'],
    cholera: ['kolera'],
    outbreak: ['wabak'],
    earthquake: ['gempa bumi'],
    cyclone: ['siklon'],
    evacuation: ['pemindahan'],
    mobilization: ['mobilisasi'],
    curfew: ['perintah berkurung'],
    coup: ['rampasan kuasa'],
    airstrike: ['serangan udara'],
    dam: ['empangan'],
    drought: ['kemarau'],
    famine: ['kebuluran'],
    plague: ['wabak'],
    radiation: ['sinaran'],
    refugee: ['pelarian'],
  },
  si: {
    flood: ['ගංවතුර'],
    landslide: ['නායයෑම'],
    cholera: ['කොලරා'],
    outbreak: ['වසංගත'],
    earthquake: ['භූමිකම්පා'],
    cyclone: ['සුළි කුණාටු'],
    evacuation: ['ඉවත්'],
    mobilization: ['mobilization'],
    curfew: ['ඇඳිරි නීතිය'],
    coup: ['කුමන්ත්‍රණය'],
    airstrike: ['ගුවන් ප්‍රහාරය'],
    dam: ['වේල්ල'],
    drought: ['නියඟය'],
    famine: ['සාගතය'],
    plague: ['වසංගතය'],
    radiation: ['විකිරණ'],
    refugee: ['සරණාගත'],
  },
  ta: {
    flood: ['வெள்ளம்'],
    landslide: ['நிலச்சரிவு'],
    cholera: ['காலரா'],
    outbreak: ['தொற்றுநோய்'],
    earthquake: ['நிலநடுக்கம்'],
    cyclone: ['சூறாவளி'],
    evacuation: ['வெளியேற்றம்'],
    mobilization: ['mobilization'],
    curfew: ['ஊரடங்கு'],
    coup: ['ஆட்சிக்கவிழ்ப்பு'],
    airstrike: ['வான்தாக்குதல்'],
    dam: ['அணைய'],
    drought: ['வறட்சி'],
    famine: ['பஞ்சம்'],
    plague: ['பிளேக்'],
    radiation: ['கதிர்வீச்சு'],
    refugee: ['அகதி'],
  },
  ku: {
    flood: ['lehî'],
    landslide: ['herikîna erdê'],
    cholera: ['kolerayê'],
    outbreak: ['belavbûn'],
    earthquake: ['erdhej'],
    cyclone: ['bager'],
    evacuation: ['valakirin'],
    mobilization: ['seferberî'],
    curfew: ['qedexeya derketinê'],
    coup: ['darbeyê'],
    airstrike: ['êrîşa hewayî'],
    dam: ['bendav'],
    drought: ['ziwa'],
    famine: ['birçîbûn'],
    plague: ['taûn'],
    radiation: ['tîrêj'],
    refugee: ['penaber'],
  },
  ckb: {
    flood: ['لافاو'],
    landslide: ['شکانی زەوی'],
    cholera: ['کۆلیرا'],
    outbreak: ['بڵاوبوونەوە'],
    earthquake: ['بوومەلەرزە'],
    cyclone: ['گەردەلوول'],
    evacuation: ['بەتاڵکردن'],
    mobilization: ['mobilization'],
    curfew: ['قاچەغەی هاتوچۆ'],
    coup: ['کودەتا'],
    airstrike: ['هێرشی ئاسمانی'],
    dam: ['بەنداو'],
    drought: ['وشکەساڵی'],
    famine: ['برسێتی'],
    plague: ['تاعوون'],
    radiation: ['تیشک'],
    refugee: ['پەنابەر'],
  },
  ky: {
    flood: ['суу ташкыны'],
    landslide: ['көчкү'],
    cholera: ['холера'],
    outbreak: ['жарылуу'],
    earthquake: ['жер титирөө'],
    cyclone: ['циклон'],
    evacuation: ['эвакуация'],
    mobilization: ['мобилизация'],
    curfew: ['коменданттык саат'],
    coup: ['төңкөрүш'],
    airstrike: ['авиасогуш'],
    dam: ['плотина'],
    drought: ['кургакчылык'],
    famine: ['ачарчылык'],
    plague: ['чума'],
    radiation: ['радиация'],
    refugee: ['качкын'],
  },
  tg: {
    flood: ['сил'],
    landslide: ['яр'],
    cholera: ['вабо'],
    outbreak: ['шуюъ'],
    earthquake: ['заминларза'],
    cyclone: ['тӯфон'],
    evacuation: ['эвакуатсия'],
    mobilization: ['сафарбарӣ'],
    curfew: ['соати комендантӣ'],
    coup: ['табаддулот'],
    airstrike: ['ҳамлаи ҳавоӣ'],
    dam: ['сарбанд'],
    drought: ['хушксолӣ'],
    famine: ['қаҳтӣ'],
    plague: ['тоун'],
    radiation: ['радиатсия'],
    refugee: ['паноҳанда'],
  },
  uz: {
    flood: ['suv toshqini'],
    landslide: ['ko\'chki'],
    cholera: ['vabo'],
    outbreak: ['avj olish'],
    earthquake: ['zilzila'],
    cyclone: ['siklon'],
    evacuation: ['evakuatsiya'],
    mobilization: ['safarbarlik'],
    curfew: ['komendantlik soati'],
    coup: ['to\'ntarish'],
    airstrike: ['havo hujumi'],
    dam: ['to\'g\'on'],
    drought: ['qurg\'oqchilik'],
    famine: ['ochlik'],
    plague: ['o\'lat'],
    radiation: ['radiatsiya'],
    refugee: ['qochqin'],
  },
  ka: {
    flood: ['წყალდიდობა'],
    landslide: ['მეწყერი'],
    cholera: ['ქოლერა'],
    outbreak: ['გავრცელება'],
    earthquake: ['მიწისძვრა'],
    cyclone: ['ციკლონი'],
    evacuation: ['ევაკუაცია'],
    mobilization: ['მობილიზაცია'],
    curfew: ['კომენდანტის საათი'],
    coup: ['გადატრიალება'],
    airstrike: ['ავიადარტყმა'],
    dam: ['კაშხალი'],
    drought: ['გვალვა'],
    famine: ['შიმშილი'],
    plague: ['ჟამი'],
    radiation: ['რადიაცია'],
    refugee: ['ლტოლვილი'],
  },
  hy: {
    flood: ['ջրհեղեղ'],
    landslide: ['սողանք'],
    cholera: ['խոլերա'],
    outbreak: ['բռնկում'],
    earthquake: ['երկրաշարժ'],
    cyclone: ['ցիկլոն'],
    evacuation: ['տարհանում'],
    mobilization: ['զորահավաք'],
    curfew: ['պարետային ժամ'],
    coup: ['հեղաշրջում'],
    airstrike: ['օդային հարված'],
    dam: ['ամբարտակ'],
    drought: ['երաշտ'],
    famine: ['սով'],
    plague: ['ժանտախտ'],
    radiation: ['ճառագայթում'],
    refugee: ['փախստական'],
  },
  az: {
    flood: ['daşqın'],
    landslide: ['sürüşmə'],
    cholera: ['vəba'],
    outbreak: ['yayılma'],
    earthquake: ['zəlzələ'],
    cyclone: ['siklon'],
    evacuation: ['evakuasiya'],
    mobilization: ['səfərbərlik'],
    curfew: ['komendant saatı'],
    coup: ['çevriliş'],
    airstrike: ['hava zərbəsi'],
    dam: ['bənd'],
    drought: ['quraqlıq'],
    famine: ['qıtlıq'],
    plague: ['taun'],
    radiation: ['radiasiya'],
    refugee: ['qaçqın'],
  },
  sr: {
    flood: ['поплава', 'poplava'],
    landslide: ['клизиште', 'klizište'],
    cholera: ['колера', 'kolera'],
    outbreak: ['епидемија', 'epidemija'],
    earthquake: ['земљотрес', 'zemljotres'],
    cyclone: ['циклон', 'ciklon'],
    evacuation: ['евакуација', 'evakuacija'],
    mobilization: ['мобилизација', 'mobilizacija'],
    curfew: ['полицијски час', 'policijski čas'],
    coup: ['пуч', 'puc'],
    airstrike: ['ваздушни удар', 'vazdušni udar'],
    dam: ['брана', 'brana'],
    drought: ['суша', 'suša'],
    famine: ['глад', 'glad'],
    plague: ['куга', 'kuga'],
    radiation: ['радијација', 'radijacija'],
    refugee: ['избеглица', 'izbeglica'],
  },
}

function fold(value: string): string {
  return value
    .normalize('NFKC')
    .replace(/_/g, ' ')
    .toLowerCase()
    .replace(/\s+/g, ' ')
    .trim()
}

export const HAZARD_TERMS: HazardTerm[] = Object.entries(RAW).flatMap(([lang, concepts]) =>
  Object.entries(concepts).flatMap(([concept, terms]) =>
    (terms ?? []).map((term) => ({
      lang,
      concept: concept as HazardConcept,
      term,
      status: HAZARD_TERM_STATUS,
    })),
  ),
)

const BY_LANG = new Map<string, HazardTerm[]>()
for (const row of HAZARD_TERMS) {
  const list = BY_LANG.get(row.lang) ?? []
  list.push(row)
  BY_LANG.set(row.lang, list)
}

export function matchHazardTitle(title: string, lang: string): HazardTerm | null {
  const hay = fold(title)
  if (!hay) return null
  const terms = BY_LANG.get(lang) ?? []
  for (const row of terms) {
    const needle = fold(row.term)
    if (needle && hay.includes(needle)) return row
  }
  return null
}
