/**
 * Wikimedia project → primary country mapping for wiki_top daily rows.
 * Region id is resolved at ingest time against crisis_regions level=0.
 */
export const WIKI_PROJECTS = [
  'en.wikipedia',
  'ar.wikipedia',
  'fa.wikipedia',
  'uk.wikipedia',
  'ru.wikipedia',
  'ne.wikipedia',
  'bn.wikipedia',
  'hi.wikipedia',
  'ur.wikipedia',
  'ps.wikipedia',
  'my.wikipedia',
  'th.wikipedia',
  'vi.wikipedia',
  'id.wikipedia',
  'tl.wikipedia',
  'sw.wikipedia',
  'am.wikipedia',
  'so.wikipedia',
  'ha.wikipedia',
  'yo.wikipedia',
  'fr.wikipedia',
  'es.wikipedia',
  'pt.wikipedia',
  'tr.wikipedia',
  'he.wikipedia',
  'ko.wikipedia',
  'ja.wikipedia',
  'zh.wikipedia',
  'ms.wikipedia',
  'si.wikipedia',
  'ta.wikipedia',
  'ku.wikipedia',
  'ckb.wikipedia',
  'ky.wikipedia',
  'tg.wikipedia',
  'uz.wikipedia',
  'ka.wikipedia',
  'hy.wikipedia',
  'az.wikipedia',
  'sr.wikipedia',
] as const

export type WikiProject = (typeof WIKI_PROJECTS)[number]

/** Main country for the language edition. Edit when a project should attach elsewhere. */
export const WIKI_PROJECT_ISO3: Record<WikiProject, string> = {
  'en.wikipedia': 'USA',
  'ar.wikipedia': 'EGY',
  'fa.wikipedia': 'IRN',
  'uk.wikipedia': 'UKR',
  'ru.wikipedia': 'RUS',
  'ne.wikipedia': 'NPL',
  'bn.wikipedia': 'BGD',
  'hi.wikipedia': 'IND',
  'ur.wikipedia': 'PAK',
  'ps.wikipedia': 'AFG',
  'my.wikipedia': 'MMR',
  'th.wikipedia': 'THA',
  'vi.wikipedia': 'VNM',
  'id.wikipedia': 'IDN',
  'tl.wikipedia': 'PHL',
  'sw.wikipedia': 'TZA',
  'am.wikipedia': 'ETH',
  'so.wikipedia': 'SOM',
  'ha.wikipedia': 'NGA',
  'yo.wikipedia': 'NGA',
  'fr.wikipedia': 'FRA',
  'es.wikipedia': 'ESP',
  'pt.wikipedia': 'BRA',
  'tr.wikipedia': 'TUR',
  'he.wikipedia': 'ISR',
  'ko.wikipedia': 'KOR',
  'ja.wikipedia': 'JPN',
  'zh.wikipedia': 'CHN',
  'ms.wikipedia': 'MYS',
  'si.wikipedia': 'LKA',
  'ta.wikipedia': 'IND',
  'ku.wikipedia': 'IRQ',
  'ckb.wikipedia': 'IRQ',
  'ky.wikipedia': 'KGZ',
  'tg.wikipedia': 'TJK',
  'uz.wikipedia': 'UZB',
  'ka.wikipedia': 'GEO',
  'hy.wikipedia': 'ARM',
  'az.wikipedia': 'AZE',
  'sr.wikipedia': 'SRB',
}

export function wikiProjectLang(project: string): string {
  return project.split('.')[0] ?? project
}
