/**
 * ISO 3166-1 alpha-2 codes offered at signup / first-touch country registration.
 * DATA ONLY. Anything not listed is rejected — do not accept a free-typed
 * country string (that is how a false declaration gets laundered).
 */

export const SIGNUP_COUNTRY_CODES = [
  'KR',
  'US',
  'JP',
  'CN',
  'GB',
  'DE',
  'FR',
  'IT',
  'ES',
  'NL',
  'BE',
  'AT',
  'CH',
  'SE',
  'NO',
  'DK',
  'FI',
  'IE',
  'PT',
  'PL',
  'CZ',
  'AU',
  'NZ',
  'CA',
  'MX',
  'BR',
  'AR',
  'IN',
  'SG',
  'HK',
  'TW',
  'TH',
  'VN',
  'ID',
  'MY',
  'PH',
  'AE',
  'SA',
  'QA',
  'IL',
  'ZA',
  'NG',
  'EG',
  'TR',
] as const

export type SignupCountryCode = (typeof SIGNUP_COUNTRY_CODES)[number]

export const SIGNUP_COUNTRY_LABELS: Record<
  SignupCountryCode,
  {
    ko: string
    en: string
    ja: string
    'zh-TW': string
    fr: string
    es: string
    pt: string
    ar: string
  }
> = {
  KR: {
    ko: '대한민국 (KR)',
    en: 'South Korea (KR)',
    ja: '韓国 (KR)',
    'zh-TW': '南韓 (KR)',
    fr: 'Corée du Sud (KR)',
    es: 'Corea del Sur (KR)',
    pt: 'Coreia do Sul (KR)',
    ar: 'كوريا الجنوبية (KR)',
  },
  US: {
    ko: '미국 (US)',
    en: 'United States (US)',
    ja: 'アメリカ (US)',
    'zh-TW': '美國 (US)',
    fr: 'États-Unis (US)',
    es: 'Estados Unidos (US)',
    pt: 'Estados Unidos (US)',
    ar: 'الولايات المتحدة (US)',
  },
  JP: {
    ko: '일본 (JP)',
    en: 'Japan (JP)',
    ja: '日本 (JP)',
    'zh-TW': '日本 (JP)',
    fr: 'Japon (JP)',
    es: 'Japón (JP)',
    pt: 'Japão (JP)',
    ar: 'اليابان (JP)',
  },
  CN: {
    ko: '중국 (CN)',
    en: 'China (CN)',
    ja: '中国 (CN)',
    'zh-TW': '中國 (CN)',
    fr: 'Chine (CN)',
    es: 'China (CN)',
    pt: 'China (CN)',
    ar: 'الصين (CN)',
  },
  GB: {
    ko: '영국 (GB)',
    en: 'United Kingdom (GB)',
    ja: 'イギリス (GB)',
    'zh-TW': '英國 (GB)',
    fr: 'Royaume-Uni (GB)',
    es: 'Reino Unido (GB)',
    pt: 'Reino Unido (GB)',
    ar: 'المملكة المتحدة (GB)',
  },
  DE: {
    ko: '독일 (DE)',
    en: 'Germany (DE)',
    ja: 'ドイツ (DE)',
    'zh-TW': '德國 (DE)',
    fr: 'Allemagne (DE)',
    es: 'Alemania (DE)',
    pt: 'Alemanha (DE)',
    ar: 'ألمانيا (DE)',
  },
  FR: {
    ko: '프랑스 (FR)',
    en: 'France (FR)',
    ja: 'フランス (FR)',
    'zh-TW': '法國 (FR)',
    fr: 'France (FR)',
    es: 'Francia (FR)',
    pt: 'França (FR)',
    ar: 'فرنسا (FR)',
  },
  IT: {
    ko: '이탈리아 (IT)',
    en: 'Italy (IT)',
    ja: 'イタリア (IT)',
    'zh-TW': '義大利 (IT)',
    fr: 'Italie (IT)',
    es: 'Italia (IT)',
    pt: 'Itália (IT)',
    ar: 'إيطاليا (IT)',
  },
  ES: {
    ko: '스페인 (ES)',
    en: 'Spain (ES)',
    ja: 'スペイン (ES)',
    'zh-TW': '西班牙 (ES)',
    fr: 'Espagne (ES)',
    es: 'España (ES)',
    pt: 'Espanha (ES)',
    ar: 'إسبانيا (ES)',
  },
  NL: {
    ko: '네덜란드 (NL)',
    en: 'Netherlands (NL)',
    ja: 'オランダ (NL)',
    'zh-TW': '荷蘭 (NL)',
    fr: 'Pays-Bas (NL)',
    es: 'Países Bajos (NL)',
    pt: 'Países Baixos (NL)',
    ar: 'هولندا (NL)',
  },
  BE: {
    ko: '벨기에 (BE)',
    en: 'Belgium (BE)',
    ja: 'ベルギー (BE)',
    'zh-TW': '比利時 (BE)',
    fr: 'Belgique (BE)',
    es: 'Bélgica (BE)',
    pt: 'Bélgica (BE)',
    ar: 'بلجيكا (BE)',
  },
  AT: {
    ko: '오스트리아 (AT)',
    en: 'Austria (AT)',
    ja: 'オーストリア (AT)',
    'zh-TW': '奧地利 (AT)',
    fr: 'Autriche (AT)',
    es: 'Austria (AT)',
    pt: 'Áustria (AT)',
    ar: 'النمسا (AT)',
  },
  CH: {
    ko: '스위스 (CH)',
    en: 'Switzerland (CH)',
    ja: 'スイス (CH)',
    'zh-TW': '瑞士 (CH)',
    fr: 'Suisse (CH)',
    es: 'Suiza (CH)',
    pt: 'Suíça (CH)',
    ar: 'سويسرا (CH)',
  },
  SE: {
    ko: '스웨덴 (SE)',
    en: 'Sweden (SE)',
    ja: 'スウェーデン (SE)',
    'zh-TW': '瑞典 (SE)',
    fr: 'Suède (SE)',
    es: 'Suecia (SE)',
    pt: 'Suécia (SE)',
    ar: 'السويد (SE)',
  },
  NO: {
    ko: '노르웨이 (NO)',
    en: 'Norway (NO)',
    ja: 'ノルウェー (NO)',
    'zh-TW': '挪威 (NO)',
    fr: 'Norvège (NO)',
    es: 'Noruega (NO)',
    pt: 'Noruega (NO)',
    ar: 'النرويج (NO)',
  },
  DK: {
    ko: '덴마크 (DK)',
    en: 'Denmark (DK)',
    ja: 'デンマーク (DK)',
    'zh-TW': '丹麥 (DK)',
    fr: 'Danemark (DK)',
    es: 'Dinamarca (DK)',
    pt: 'Dinamarca (DK)',
    ar: 'الدنمارك (DK)',
  },
  FI: {
    ko: '핀란드 (FI)',
    en: 'Finland (FI)',
    ja: 'フィンランド (FI)',
    'zh-TW': '芬蘭 (FI)',
    fr: 'Finlande (FI)',
    es: 'Finlandia (FI)',
    pt: 'Finlândia (FI)',
    ar: 'فنلندا (FI)',
  },
  IE: {
    ko: '아일랜드 (IE)',
    en: 'Ireland (IE)',
    ja: 'アイルランド (IE)',
    'zh-TW': '愛爾蘭 (IE)',
    fr: 'Irlande (IE)',
    es: 'Irlanda (IE)',
    pt: 'Irlanda (IE)',
    ar: 'أيرلندا (IE)',
  },
  PT: {
    ko: '포르투갈 (PT)',
    en: 'Portugal (PT)',
    ja: 'ポルトガル (PT)',
    'zh-TW': '葡萄牙 (PT)',
    fr: 'Portugal (PT)',
    es: 'Portugal (PT)',
    pt: 'Portugal (PT)',
    ar: 'البرتغال (PT)',
  },
  PL: {
    ko: '폴란드 (PL)',
    en: 'Poland (PL)',
    ja: 'ポーランド (PL)',
    'zh-TW': '波蘭 (PL)',
    fr: 'Pologne (PL)',
    es: 'Polonia (PL)',
    pt: 'Polônia (PL)',
    ar: 'بولندا (PL)',
  },
  CZ: {
    ko: '체코 (CZ)',
    en: 'Czech Republic (CZ)',
    ja: 'チェコ (CZ)',
    'zh-TW': '捷克 (CZ)',
    fr: 'Tchéquie (CZ)',
    es: 'Chequia (CZ)',
    pt: 'Tchéquia (CZ)',
    ar: 'التشيك (CZ)',
  },
  AU: {
    ko: '호주 (AU)',
    en: 'Australia (AU)',
    ja: 'オーストラリア (AU)',
    'zh-TW': '澳洲 (AU)',
    fr: 'Australie (AU)',
    es: 'Australia (AU)',
    pt: 'Austrália (AU)',
    ar: 'أستراليا (AU)',
  },
  NZ: {
    ko: '뉴질랜드 (NZ)',
    en: 'New Zealand (NZ)',
    ja: 'ニュージーランド (NZ)',
    'zh-TW': '紐西蘭 (NZ)',
    fr: 'Nouvelle-Zélande (NZ)',
    es: 'Nueva Zelanda (NZ)',
    pt: 'Nova Zelândia (NZ)',
    ar: 'نيوزيلندا (NZ)',
  },
  CA: {
    ko: '캐나다 (CA)',
    en: 'Canada (CA)',
    ja: 'カナダ (CA)',
    'zh-TW': '加拿大 (CA)',
    fr: 'Canada (CA)',
    es: 'Canadá (CA)',
    pt: 'Canadá (CA)',
    ar: 'كندا (CA)',
  },
  MX: {
    ko: '멕시코 (MX)',
    en: 'Mexico (MX)',
    ja: 'メキシコ (MX)',
    'zh-TW': '墨西哥 (MX)',
    fr: 'Mexique (MX)',
    es: 'México (MX)',
    pt: 'México (MX)',
    ar: 'المكسيك (MX)',
  },
  BR: {
    ko: '브라질 (BR)',
    en: 'Brazil (BR)',
    ja: 'ブラジル (BR)',
    'zh-TW': '巴西 (BR)',
    fr: 'Brésil (BR)',
    es: 'Brasil (BR)',
    pt: 'Brasil (BR)',
    ar: 'البرازيل (BR)',
  },
  AR: {
    ko: '아르헨티나 (AR)',
    en: 'Argentina (AR)',
    ja: 'アルゼンチン (AR)',
    'zh-TW': '阿根廷 (AR)',
    fr: 'Argentine (AR)',
    es: 'Argentina (AR)',
    pt: 'Argentina (AR)',
    ar: 'الأرجنتين (AR)',
  },
  IN: {
    ko: '인도 (IN)',
    en: 'India (IN)',
    ja: 'インド (IN)',
    'zh-TW': '印度 (IN)',
    fr: 'Inde (IN)',
    es: 'India (IN)',
    pt: 'Índia (IN)',
    ar: 'الهند (IN)',
  },
  SG: {
    ko: '싱가포르 (SG)',
    en: 'Singapore (SG)',
    ja: 'シンガポール (SG)',
    'zh-TW': '新加坡 (SG)',
    fr: 'Singapour (SG)',
    es: 'Singapur (SG)',
    pt: 'Singapura (SG)',
    ar: 'سنغافورة (SG)',
  },
  HK: {
    ko: '홍콩 (HK)',
    en: 'Hong Kong (HK)',
    ja: '香港 (HK)',
    'zh-TW': '香港 (HK)',
    fr: 'Hong Kong (HK)',
    es: 'Hong Kong (HK)',
    pt: 'Hong Kong (HK)',
    ar: 'هونغ كونغ (HK)',
  },
  TW: {
    ko: '대만 (TW)',
    en: 'Taiwan (TW)',
    ja: '台湾 (TW)',
    'zh-TW': '台灣 (TW)',
    fr: 'Taïwan (TW)',
    es: 'Taiwán (TW)',
    pt: 'Taiwan (TW)',
    ar: 'تايوان (TW)',
  },
  TH: {
    ko: '태국 (TH)',
    en: 'Thailand (TH)',
    ja: 'タイ (TH)',
    'zh-TW': '泰國 (TH)',
    fr: 'Thaïlande (TH)',
    es: 'Tailandia (TH)',
    pt: 'Tailândia (TH)',
    ar: 'تايلاند (TH)',
  },
  VN: {
    ko: '베트남 (VN)',
    en: 'Vietnam (VN)',
    ja: 'ベトナム (VN)',
    'zh-TW': '越南 (VN)',
    fr: 'Vietnam (VN)',
    es: 'Vietnam (VN)',
    pt: 'Vietnã (VN)',
    ar: 'فيتنام (VN)',
  },
  ID: {
    ko: '인도네시아 (ID)',
    en: 'Indonesia (ID)',
    ja: 'インドネシア (ID)',
    'zh-TW': '印尼 (ID)',
    fr: 'Indonésie (ID)',
    es: 'Indonesia (ID)',
    pt: 'Indonésia (ID)',
    ar: 'إندونيسيا (ID)',
  },
  MY: {
    ko: '말레이시아 (MY)',
    en: 'Malaysia (MY)',
    ja: 'マレーシア (MY)',
    'zh-TW': '馬來西亞 (MY)',
    fr: 'Malaisie (MY)',
    es: 'Malasia (MY)',
    pt: 'Malásia (MY)',
    ar: 'ماليزيا (MY)',
  },
  PH: {
    ko: '필리핀 (PH)',
    en: 'Philippines (PH)',
    ja: 'フィリピン (PH)',
    'zh-TW': '菲律賓 (PH)',
    fr: 'Philippines (PH)',
    es: 'Filipinas (PH)',
    pt: 'Filipinas (PH)',
    ar: 'الفلبين (PH)',
  },
  AE: {
    ko: '아랍에미리트 (AE)',
    en: 'United Arab Emirates (AE)',
    ja: 'アラブ首長国連邦 (AE)',
    'zh-TW': '阿聯 (AE)',
    fr: 'Émirats arabes unis (AE)',
    es: 'Emiratos Árabes Unidos (AE)',
    pt: 'Emirados Árabes Unidos (AE)',
    ar: 'الإمارات (AE)',
  },
  SA: {
    ko: '사우디아라비아 (SA)',
    en: 'Saudi Arabia (SA)',
    ja: 'サウジアラビア (SA)',
    'zh-TW': '沙烏地阿拉伯 (SA)',
    fr: 'Arabie saoudite (SA)',
    es: 'Arabia Saudita (SA)',
    pt: 'Arábia Saudita (SA)',
    ar: 'المملكة العربية السعودية (SA)',
  },
  QA: {
    ko: '카타르 (QA)',
    en: 'Qatar (QA)',
    ja: 'カタール (QA)',
    'zh-TW': '卡達 (QA)',
    fr: 'Qatar (QA)',
    es: 'Catar (QA)',
    pt: 'Catar (QA)',
    ar: 'قطر (QA)',
  },
  IL: {
    ko: '이스라엘 (IL)',
    en: 'Israel (IL)',
    ja: 'イスラエル (IL)',
    'zh-TW': '以色列 (IL)',
    fr: 'Israël (IL)',
    es: 'Israel (IL)',
    pt: 'Israel (IL)',
    ar: 'إسرائيل (IL)',
  },
  ZA: {
    ko: '남아프리카 공화국 (ZA)',
    en: 'South Africa (ZA)',
    ja: '南アフリカ (ZA)',
    'zh-TW': '南非 (ZA)',
    fr: 'Afrique du Sud (ZA)',
    es: 'Sudáfrica (ZA)',
    pt: 'África do Sul (ZA)',
    ar: 'جنوب إفريقيا (ZA)',
  },
  NG: {
    ko: '나이지리아 (NG)',
    en: 'Nigeria (NG)',
    ja: 'ナイジェリア (NG)',
    'zh-TW': '奈及利亞 (NG)',
    fr: 'Nigeria (NG)',
    es: 'Nigeria (NG)',
    pt: 'Nigéria (NG)',
    ar: 'نيجيريا (NG)',
  },
  EG: {
    ko: '이집트 (EG)',
    en: 'Egypt (EG)',
    ja: 'エジプト (EG)',
    'zh-TW': '埃及 (EG)',
    fr: 'Égypte (EG)',
    es: 'Egipto (EG)',
    pt: 'Egito (EG)',
    ar: 'مصر (EG)',
  },
  TR: {
    ko: '튀르키예 (TR)',
    en: 'Turkey (TR)',
    ja: 'トルコ (TR)',
    'zh-TW': '土耳其 (TR)',
    fr: 'Turquie (TR)',
    es: 'Turquía (TR)',
    pt: 'Turquia (TR)',
    ar: 'تركيا (TR)',
  },
}

export function getSignupCountryLabel(code: SignupCountryCode, locale?: string | null): string {
  const item = SIGNUP_COUNTRY_LABELS[code]
  if (!item) return code
  if (!locale) return item.ko || item.en || code
  const loc = locale.toLowerCase()
  if (loc.startsWith('ko')) return item.ko
  if (loc.startsWith('ja')) return item.ja
  if (loc.startsWith('zh-tw') || loc.startsWith('zh-hk') || loc.includes('hant')) return item['zh-TW']
  if (loc.startsWith('fr')) return item.fr
  if (loc.startsWith('es')) return item.es
  if (loc.startsWith('pt')) return item.pt
  if (loc.startsWith('ar')) return item.ar
  return item.en || item.ko || code
}

export function normalizeSignupCountry(raw: unknown): SignupCountryCode | null {
  if (typeof raw !== 'string') return null
  const code = raw.trim().toUpperCase()
  return (SIGNUP_COUNTRY_CODES as readonly string[]).includes(code) ? (code as SignupCountryCode) : null
}
