/**
 * Display names for the leagues the sports gateway can open.
 * Keys are the English names stored on MATCH instruments. Odds feeds sometimes
 * shorten them ("Leeds"); CLUB_ALIAS points those at the full key.
 * ko / ja / zh-TW only — other locales keep the English name.
 */

export type ClubLocaleName = { ko: string; ja: string; 'zh-TW': string }

type Row = [string, string, string, string]

function rows(list: readonly Row[]): Record<string, ClubLocaleName> {
  const out: Record<string, ClubLocaleName> = {}
  for (const [en, ko, ja, zh] of list) out[en] = { ko, ja, 'zh-TW': zh }
  return out
}

const PREMIER: readonly Row[] = [
  ['Arsenal', '아스날', 'アーセナル', '阿森納'],
  ['Aston Villa', '아스톤 빌라', 'アストン・ヴィラ', '阿斯頓維拉'],
  ['Bournemouth', '본머스', 'ボーンマス', '伯恩茅斯'],
  ['Brentford', '브렌트퍼드', 'ブレントフォード', '布倫特福德'],
  ['Brighton and Hove Albion', '브라이튼', 'ブライトン', '布萊頓'],
  ['Burnley', '번리', 'バーンリー', '伯恩利'],
  ['Chelsea', '첼시', 'チェルシー', '切爾西'],
  ['Crystal Palace', '크리스탈 팰리스', 'クリスタル・パレス', '水晶宮'],
  ['Everton', '에버턴', 'エヴァートン', '埃弗頓'],
  ['Fulham', '풀럼', 'フラム', '富勒姆'],
  ['Leeds United', '리즈 유나이티드', 'リーズ', '里茲聯'],
  ['Liverpool', '리버풀', 'リバプール', '利物浦'],
  ['Manchester City', '맨체스터 시티', 'マンチェスター・シティ', '曼城'],
  ['Manchester United', '맨체스터 유나이티드', 'マンチェスター・ユナイテッド', '曼聯'],
  ['Newcastle United', '뉴캐슬', 'ニューカッスル', '紐卡斯爾'],
  ['Nottingham Forest', '노팅엄 포레스트', 'ノッティンガム', '諾丁漢森林'],
  ['Sunderland', '선덜랜드', 'サンダーランド', '桑德蘭'],
  ['Tottenham Hotspur', '토트넘', 'トッテナム', '熱刺'],
  ['West Ham United', '웨스트햄', 'ウェストハム', '西漢姆'],
  ['Wolverhampton Wanderers', '울버햄튼', 'ウルブス', '狼隊'],
]

const LIGA: readonly Row[] = [
  ['Alaves', '알라베스', 'アラベス', '阿拉維斯'],
  ['Athletic Club', '아틀레틱 빌바오', 'アスレティック', '畢爾巴鄂競技'],
  ['Atletico Madrid', '아틀레티코 마드리드', 'アトレティコ', '馬德里競技'],
  ['Barcelona', '바르셀로나', 'バルセロナ', '巴塞隆納'],
  ['Celta Vigo', '셀타 비고', 'セルタ', '切爾塔'],
  ['Elche', '엘체', 'エルチェ', '埃爾切'],
  ['Espanyol', '에스파뇰', 'エスパニョール', '西班牙人'],
  ['Getafe', '헤타페', 'ヘタフェ', '赫塔費'],
  ['Girona', '지로나', 'ジローナ', '赫羅納'],
  ['Levante', '레반테', 'レバンテ', '萊萬特'],
  ['Mallorca', '마요르카', 'マジョルカ', '馬略卡'],
  ['Osasuna', '오사수나', 'オサスナ', '奧薩蘇納'],
  ['Rayo Vallecano', '라요 바예카노', 'ラージョ', '巴列卡諾'],
  ['Real Betis', '레알 베티스', 'ベティス', '皇家貝蒂斯'],
  ['Real Madrid', '레알 마드리드', 'レアル・マドリード', '皇家馬德里'],
  ['Real Oviedo', '레알 오비에도', 'オビエド', '奧維耶多'],
  ['Real Sociedad', '레알 소시에다드', 'レアル・ソシエダ', '皇家社會'],
  ['Sevilla', '세비야', 'セビージャ', '塞維利亞'],
  ['Valencia', '발렌시아', 'バレンシア', '瓦倫西亞'],
  ['Villarreal', '비야레알', 'ビジャレアル', '比利亞雷亞爾'],
]

const SERIE: readonly Row[] = [
  ['Atalanta', '아탈란타', 'アタランタ', '亞特蘭大'],
  ['Bologna', '볼로냐', 'ボローニャ', '波隆納'],
  ['Cagliari', '칼리아리', 'カリアリ', '卡利亞里'],
  ['Como', '코모', 'コモ', '科莫'],
  ['Cremonese', '크레모네세', 'クレモネーゼ', '克雷莫內塞'],
  ['Fiorentina', '피오렌티나', 'フィオレンティーナ', '費倫提納'],
  ['Genoa', '제노아', 'ジェノア', '熱那亞'],
  ['Inter Milan', '인터 밀란', 'インテル', '國際米蘭'],
  ['Juventus', '유벤투스', 'ユベントス', '尤文圖斯'],
  ['Lazio', '라치오', 'ラツィオ', '拉齊奧'],
  ['Lecce', '레체', 'レッチェ', '萊切'],
  ['AC Milan', 'AC 밀란', 'ミラン', 'AC米蘭'],
  ['Napoli', '나폴리', 'ナポリ', '那不勒斯'],
  ['Parma', '파르마', 'パルマ', '帕爾馬'],
  ['Pisa', '피사', 'ピサ', '比薩'],
  ['AS Roma', 'AS 로마', 'ローマ', '羅馬'],
  ['Sassuolo', '사수올로', 'サッスオーロ', '薩索洛'],
  ['Torino', '토리노', 'トリノ', '都靈'],
  ['Udinese', '우디네세', 'ウディネーゼ', '烏迪內斯'],
  ['Hellas Verona', '베로나', 'ヴェローナ', '維羅納'],
]

const BUNDES: readonly Row[] = [
  ['Augsburg', '아우크스부르크', 'アウクスブルク', '奧格斯堡'],
  ['Bayern Munich', '바이에른 뮌헨', 'バイエルン', '拜仁慕尼黑'],
  ['Werder Bremen', '베르더 브레멘', 'ブレーメン', '雲達不萊梅'],
  ['Borussia Dortmund', '도르트문트', 'ドルトムント', '多特蒙德'],
  ['Eintracht Frankfurt', '프랑크푸르트', 'フランクフルト', '法蘭克福'],
  ['Freiburg', '프라이부르크', 'フライブルク', '弗賴堡'],
  ['Hamburger SV', '함부르크', 'ハンブルガー', '漢堡'],
  ['Heidenheim', '하이덴하임', 'ハイデンハイム', '海登海姆'],
  ['Hoffenheim', '호펜하임', 'ホッフェンハイム', '霍芬海姆'],
  ['Koln', '쾰른', 'ケルン', '科隆'],
  ['RB Leipzig', 'RB 라이프치히', 'ライプツィヒ', '萊比錫紅牛'],
  ['Bayer Leverkusen', '레버쿠젠', 'レバークーゼン', '勒沃庫森'],
  ['Mainz', '마인츠', 'マインツ', '美因茨'],
  ['Borussia Monchengladbach', '묀헨글라트바흐', 'グラートバッハ', '門興'],
  ['St Pauli', '장크트 파울리', 'ザンクトパウリ', '聖保利'],
  ['Stuttgart', '슈투트가르트', 'シュトゥットガルト', '斯圖加特'],
  ['Union Berlin', '우니온 베를린', 'ウニオン・ベルリン', '柏林聯合'],
  ['Wolfsburg', '볼프스부르크', 'ヴォルフスブルク', '沃爾夫斯堡'],
]

const LIGUE: readonly Row[] = [
  ['Angers', '앙제', 'アンジェ', '昂熱'],
  ['Auxerre', '오세르', 'オセール', '歐塞爾'],
  ['Brest', '브레스트', 'ブレスト', '布雷斯特'],
  ['Le Havre', '르아브르', 'ル・アーヴル', '勒阿弗爾'],
  ['Lens', '랑스', 'ランス', '朗斯'],
  ['Lille', '릴', 'リール', '里爾'],
  ['Lorient', '로리앙', 'ロリアン', '洛里昂'],
  ['Lyon', '리옹', 'リヨン', '里昂'],
  ['Marseille', '마르세유', 'マルセイユ', '馬賽'],
  ['Metz', '메스', 'メス', '梅斯'],
  ['Monaco', '모나코', 'モナコ', '摩納哥'],
  ['Nantes', '낭트', 'ナント', '南特'],
  ['Nice', '니스', 'ニース', '尼斯'],
  ['Paris FC', '파리 FC', 'パリFC', '巴黎FC'],
  ['Paris Saint Germain', '파리 생제르맹', 'パリ・サンジェルマン', '巴黎聖日耳曼'],
  ['Rennes', '렌', 'レンヌ', '雷恩'],
  ['Strasbourg', '스트라스부르', 'ストラスブール', '斯特拉斯堡'],
  ['Toulouse', '툴루즈', 'トゥールーズ', '圖盧茲'],
]

const MLB: readonly Row[] = [
  ['Arizona Diamondbacks', '애리조나 다이아몬드백스', 'ダイヤモンドバックス', '響尾蛇'],
  ['Atlanta Braves', '애틀랜타 브레이브스', 'ブレーブス', '勇士'],
  ['Baltimore Orioles', '볼티모어 오리올스', 'オリオールズ', '金鶯'],
  ['Boston Red Sox', '보스턴 레드삭스', 'レッドソックス', '紅襪'],
  ['Chicago Cubs', '시카고 컵스', 'カブス', '小熊'],
  ['Chicago White Sox', '시카고 화이트삭스', 'ホワイトソックス', '白襪'],
  ['Cincinnati Reds', '신시내티 레즈', 'レッズ', '紅人'],
  ['Cleveland Guardians', '클리블랜드 가디언즈', 'ガーディアンズ', '守護者'],
  ['Colorado Rockies', '콜로라도 로키스', 'ロッキーズ', '洛磯'],
  ['Detroit Tigers', '디트로이트 타이거스', 'タイガース', '老虎'],
  ['Houston Astros', '휴스턴 애스트로스', 'アストロズ', '太空人'],
  ['Kansas City Royals', '캔자스시티 로열스', 'ロイヤルズ', '皇家'],
  ['Los Angeles Angels', 'LA 에인절스', 'エンゼルス', '天使'],
  ['Los Angeles Dodgers', '로스앤젤레스 다저스', 'ドジャース', '道奇'],
  ['Miami Marlins', '마이애미 말린스', 'マーリンズ', '馬林魚'],
  ['Milwaukee Brewers', '밀워키 브루어스', 'ブルワーズ', '釀酒人'],
  ['Minnesota Twins', '미네소타 트윈스', 'ツインズ', '雙城'],
  ['New York Mets', '뉴욕 메츠', 'メッツ', '大都會'],
  ['New York Yankees', '뉴욕 양키스', 'ヤンキース', '洋基'],
  ['Athletics', '애슬레틱스', 'アスレチックス', '運動家'],
  ['Philadelphia Phillies', '필라델피아 필리스', 'フィリーズ', '費城人'],
  ['Pittsburgh Pirates', '피츠버그 파이리츠', 'パイレーツ', '海盜'],
  ['San Diego Padres', '샌디에이고 파드리스', 'パドレス', '教士'],
  ['San Francisco Giants', '샌프란시스코 자이언츠', 'ジャイアンツ', '巨人'],
  ['Seattle Mariners', '시애틀 매리너스', 'マリナーズ', '水手'],
  ['St Louis Cardinals', '세인트루이스 카디널스', 'カージナルス', '紅雀'],
  ['Tampa Bay Rays', '탬파베이 레이스', 'レイズ', '光芒'],
  ['Texas Rangers', '텍사스 레인저스', 'レンジャーズ', '遊騎兵'],
  ['Toronto Blue Jays', '토론토 블루제이스', 'ブルージェイズ', '藍鳥'],
  ['Washington Nationals', '워싱턴 내셔널스', 'ナショナルズ', '國民'],
]

const NBA: readonly Row[] = [
  ['Atlanta Hawks', '애틀랜타 호크스', 'ホークス', '老鷹'],
  ['Boston Celtics', '보스턴 셀틱스', 'セルティックス', '塞爾蒂克'],
  ['Brooklyn Nets', '브루클린 네츠', 'ネッツ', '籃網'],
  ['Charlotte Hornets', '샬럿 호네츠', 'ホーネッツ', '黃蜂'],
  ['Chicago Bulls', '시카고 불스', 'ブルズ', '公牛'],
  ['Cleveland Cavaliers', '클리블랜드 캐벌리어스', 'キャバリアーズ', '騎士'],
  ['Dallas Mavericks', '댈러스 매버릭스', 'マーベリックス', '獨行俠'],
  ['Denver Nuggets', '덴버 너게츠', 'ナゲッツ', '金塊'],
  ['Detroit Pistons', '디트로이트 피스턴스', 'ピストンズ', '活塞'],
  ['Golden State Warriors', '골든스테이트 워리어스', 'ウォリアーズ', '勇士'],
  ['Houston Rockets', '휴스턴 로케츠', 'ロケッツ', '火箭'],
  ['Indiana Pacers', '인디애나 페이서스', 'ペイサーズ', '溜馬'],
  ['Los Angeles Clippers', 'LA 클리퍼스', 'クリッパーズ', '快艇'],
  ['Los Angeles Lakers', '로스앤젤레스 레이커스', 'レイカーズ', '湖人'],
  ['Memphis Grizzlies', '멤피스 그리즐리스', 'グリズリーズ', '灰熊'],
  ['Miami Heat', '마이애미 히트', 'ヒート', '熱火'],
  ['Milwaukee Bucks', '밀워키 벅스', 'バックス', '公鹿'],
  ['Minnesota Timberwolves', '미네소타 팀버울브스', 'ティンバーウルブズ', '灰狼'],
  ['New Orleans Pelicans', '뉴올리언스 펠리컨스', 'ペリカンズ', '鵜鶘'],
  ['New York Knicks', '뉴욕 닉스', 'ニックス', '尼克'],
  ['Oklahoma City Thunder', '오클라호마시티 썬더', 'サンダー', '雷霆'],
  ['Orlando Magic', '올랜도 매직', 'マジック', '魔術'],
  ['Philadelphia 76ers', '필라델피아 세븐티식서스', 'シクサーズ', '七六人'],
  ['Phoenix Suns', '피닉스 선즈', 'サンズ', '太陽'],
  ['Portland Trail Blazers', '포틀랜드 트레일블레이저스', 'ブレイザーズ', '拓荒者'],
  ['Sacramento Kings', '새크라멘토 킹스', 'キングス', '國王'],
  ['San Antonio Spurs', '샌안토니오 스퍼스', 'スパーズ', '馬刺'],
  ['Toronto Raptors', '토론토 랩터스', 'ラプターズ', '暴龍'],
  ['Utah Jazz', '유타 재즈', 'ジャズ', '爵士'],
  ['Washington Wizards', '워싱턴 위저즈', 'ウィザーズ', '巫師'],
]

const NFL: readonly Row[] = [
  ['Arizona Cardinals', '애리조나 카디널스', 'カージナルス', '紅雀'],
  ['Atlanta Falcons', '애틀랜타 팰컨스', 'ファルコンズ', '獵鷹'],
  ['Baltimore Ravens', '볼티모어 레이븐스', 'レイブンズ', '烏鴉'],
  ['Buffalo Bills', '버펄로 빌스', 'ビルズ', '比爾'],
  ['Carolina Panthers', '캐롤라이나 팬서스', 'パンサーズ', '黑豹'],
  ['Chicago Bears', '시카고 베어스', 'ベアーズ', '熊'],
  ['Cincinnati Bengals', '신시내티 벵골스', 'ベンガルズ', '猛虎'],
  ['Cleveland Browns', '클리블랜드 브라운스', 'ブラウンズ', '布朗'],
  ['Dallas Cowboys', '댈러스 카우보이스', 'カウボーイズ', '牛仔'],
  ['Denver Broncos', '덴버 브롱코스', 'ブロンコス', '野馬'],
  ['Detroit Lions', '디트로이트 라이온스', 'ライオンズ', '獅子'],
  ['Green Bay Packers', '그린베이 패커스', 'パッカーズ', '包裝工'],
  ['Houston Texans', '휴스턴 텍산스', 'テキサンズ', '德州人'],
  ['Indianapolis Colts', '인디애나폴리스 콜츠', 'コルツ', '小馬'],
  ['Jacksonville Jaguars', '잭슨빌 재규어스', 'ジャガーズ', '美洲虎'],
  ['Kansas City Chiefs', '캔자스시티 치프스', 'チーフス', '酋長'],
  ['Las Vegas Raiders', '라스베이거스 레이더스', 'レイダース', '突襲者'],
  ['Los Angeles Chargers', 'LA 차저스', 'チャージャーズ', '充電器'],
  ['Los Angeles Rams', 'LA 램스', 'ラムズ', '公羊'],
  ['Miami Dolphins', '마이애미 돌핀스', 'ドルフィンズ', '海豚'],
  ['Minnesota Vikings', '미네소타 바이킹스', 'バイキングス', '維京人'],
  ['New England Patriots', '뉴잉글랜드 패트리어츠', 'ペイトリオッツ', '愛國者'],
  ['New Orleans Saints', '뉴올리언스 세인츠', 'セインツ', '聖徒'],
  ['New York Giants', '뉴욕 자이언츠', 'ジャイアンツ', '巨人'],
  ['New York Jets', '뉴욕 제츠', 'ジェッツ', '噴射機'],
  ['Philadelphia Eagles', '필라델피아 이글스', 'イーグルス', '老鷹'],
  ['Pittsburgh Steelers', '피츠버그 스틸러스', 'スティーラーズ', '鋼人'],
  ['San Francisco 49ers', '샌프란시스코 포티나이너스', '49ers', '49人'],
  ['Seattle Seahawks', '시애틀 시호크스', 'シーホークス', '海鷹'],
  ['Tampa Bay Buccaneers', '탬파베이 버커니어스', 'バッカニアーズ', '海盜'],
  ['Tennessee Titans', '테네시 타이탄스', 'タイタンズ', '泰坦'],
  ['Washington Commanders', '워싱턴 커맨더스', 'コマンダーズ', '指揮官'],
]

const NHL: readonly Row[] = [
  ['Anaheim Ducks', '애너하임 덕스', 'ダックス', '鴨'],
  ['Boston Bruins', '보스턴 브루인스', 'ブルーインズ', '棕熊'],
  ['Buffalo Sabres', '버펄로 세이버스', 'セイバーズ', '軍刀'],
  ['Calgary Flames', '캘거리 플레임스', 'フレームス', '火焰'],
  ['Carolina Hurricanes', '캐롤라이나 허리케인스', 'ハリケーンズ', '颶風'],
  ['Chicago Blackhawks', '시카고 블랙호크스', 'ブラックホークス', '黑鷹'],
  ['Colorado Avalanche', '콜로라도 애벌랜치', 'アバランチ', '雪崩'],
  ['Columbus Blue Jackets', '콜럼버스 블루재킷스', 'ブルージャケッツ', '藍衣'],
  ['Dallas Stars', '댈러스 스타스', 'スターズ', '星'],
  ['Detroit Red Wings', '디트로이트 레드윙스', 'レッドウィングス', '紅翼'],
  ['Edmonton Oilers', '에드먼턴 오일러스', 'オイラーズ', '油人'],
  ['Florida Panthers', '플로리다 팬서스', 'パンサーズ', '黑豹'],
  ['Los Angeles Kings', 'LA 킹스', 'キングス', '國王'],
  ['Minnesota Wild', '미네소타 와일드', 'ワイルド', '荒野'],
  ['Montreal Canadiens', '몬트리올 캐나디언스', 'カナディアンズ', '加拿大人'],
  ['Nashville Predators', '내슈빌 프레데터스', 'プレデターズ', '掠食者'],
  ['New Jersey Devils', '뉴저지 데블스', 'デビルス', '魔鬼'],
  ['New York Islanders', '뉴욕 아일런더스', 'アイランダース', '島民'],
  ['New York Rangers', '뉴욕 레인저스', 'レンジャース', '遊騎兵'],
  ['Ottawa Senators', '오타와 세너터스', 'セネターズ', '參議員'],
  ['Philadelphia Flyers', '필라델피아 플라이어스', 'フライヤーズ', '飛人'],
  ['Pittsburgh Penguins', '피츠버그 펭귄스', 'ペンギンズ', '企鵝'],
  ['San Jose Sharks', '산호세 샤크스', 'シャークス', '鯊魚'],
  ['Seattle Kraken', '시애틀 크라켄', 'クラーケン', '海怪'],
  ['St Louis Blues', '세인트루이스 블루스', 'ブルース', '藍調'],
  ['Tampa Bay Lightning', '탬파베이 라이트닝', 'ライトニング', '閃電'],
  ['Toronto Maple Leafs', '토론토 메이플리프스', 'メープルリーフス', '楓葉'],
  ['Utah Hockey Club', '유타', 'ユタ', '猶他'],
  ['Vancouver Canucks', '밴쿠버 커넉스', 'カナックス', '加人'],
  ['Vegas Golden Knights', '베가스 골든나이츠', 'ゴールデンナイツ', '黃金騎士'],
  ['Washington Capitals', '워싱턴 캐피털스', 'キャピタルズ', '首都'],
  ['Winnipeg Jets', '위니펙 제츠', 'ジェッツ', '噴射機'],
]

export const CLUB_DISPLAY: Record<string, ClubLocaleName> = {
  ...rows(PREMIER),
  ...rows(LIGA),
  ...rows(SERIE),
  ...rows(BUNDES),
  ...rows(LIGUE),
  ...rows(MLB),
  ...rows(NBA),
  ...rows(NFL),
  ...rows(NHL),
}

/** Feed names that are shorter than the display key. */
export const CLUB_ALIAS: Record<string, string> = {
  Leeds: 'Leeds United',
  Wolves: 'Wolverhampton Wanderers',
  Spurs: 'Tottenham Hotspur',
  'Man City': 'Manchester City',
  'Man United': 'Manchester United',
  Inter: 'Inter Milan',
  Milan: 'AC Milan',
  Roma: 'AS Roma',
  Atletico: 'Atletico Madrid',
  'Atlético Madrid': 'Atletico Madrid',
  Bayern: 'Bayern Munich',
  'Bayern München': 'Bayern Munich',
  Dortmund: 'Borussia Dortmund',
  Leipzig: 'RB Leipzig',
  Leverkusen: 'Bayer Leverkusen',
  Gladbach: 'Borussia Monchengladbach',
  'Borussia Mönchengladbach': 'Borussia Monchengladbach',
  '1. FC Köln': 'Koln',
  'FC Köln': 'Koln',
  'FC Cologne': 'Koln',
  PSG: 'Paris Saint Germain',
  'Paris Saint-Germain': 'Paris Saint Germain',
  'St. Louis Cardinals': 'St Louis Cardinals',
  'St. Louis Blues': 'St Louis Blues',
  'Oakland Athletics': 'Athletics',
  'Vegas Golden Knights': 'Vegas Golden Knights',
}

export function clubDisplayName(name: string, locale: 'ko' | 'ja' | 'zh-TW'): string | null {
  const key = CLUB_ALIAS[name] ?? name
  return CLUB_DISPLAY[key]?.[locale] ?? CLUB_DISPLAY[name]?.[locale] ?? null
}
