/**
 * Trace the 12 astrological signs from an OFL symbol font.
 *
 * Font: Noto Sans Symbols Regular (SIL Open Font License 1.1).
 * Commercial or unknown-licence dingbat fonts are not allowed here.
 *
 * Run: npx tsx scripts/build-talisman-zodiac.ts
 * Expects: third_party/fonts/NotoSansSymbols-Regular.otf (gitignored).
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import opentype from 'opentype.js'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const FONT_PATH = resolve(ROOT, 'third_party/fonts/NotoSansSymbols-Regular.otf')
const OUT_PATH = resolve(ROOT, 'lib/oracle/talisman/zodiac.generated.ts')

const UNITS = 1000

export const ZODIAC_SET = [
  { id: 'aries', ch: '♈' },
  { id: 'taurus', ch: '♉' },
  { id: 'gemini', ch: '♊' },
  { id: 'cancer', ch: '♋' },
  { id: 'leo', ch: '♌' },
  { id: 'virgo', ch: '♍' },
  { id: 'libra', ch: '♎' },
  { id: 'scorpio', ch: '♏' },
  { id: 'sagittarius', ch: '♐' },
  { id: 'capricorn', ch: '♑' },
  { id: 'aquarius', ch: '♒' },
  { id: 'pisces', ch: '♓' },
] as const

function nameEn(names: opentype.Font['names'], key: string): string {
  const table = names as unknown as Record<string, Record<string, Record<string, string>>>
  return table.windows?.[key]?.en ?? table.macintosh?.[key]?.en ?? ''
}

function round(n: number): number {
  return Math.round(n * 100) / 100
}

function closedPathData(path: opentype.Path): string {
  const parts: string[] = []
  let open = false
  for (const cmd of path.commands) {
    if (cmd.type === 'M') {
      if (open) parts.push('Z')
      parts.push(`M${round(cmd.x)} ${round(cmd.y)}`)
      open = true
    } else if (cmd.type === 'L') {
      parts.push(`L${round(cmd.x)} ${round(cmd.y)}`)
    } else if (cmd.type === 'C') {
      parts.push(
        `C${round(cmd.x1)} ${round(cmd.y1)} ${round(cmd.x2)} ${round(cmd.y2)} ${round(cmd.x)} ${round(cmd.y)}`,
      )
    } else if (cmd.type === 'Q') {
      parts.push(`Q${round(cmd.x1)} ${round(cmd.y1)} ${round(cmd.x)} ${round(cmd.y)}`)
    } else if (cmd.type === 'Z') {
      parts.push('Z')
      open = false
    }
  }
  if (open) parts.push('Z')
  return parts.join('')
}

function pathData(font: opentype.Font, ch: string) {
  const glyph = font.charToGlyph(ch)
  if (!glyph || glyph.index === 0 || glyph.name === '.notdef') {
    throw new Error(`font is missing ${ch} (U+${ch.codePointAt(0)!.toString(16).toUpperCase()})`)
  }
  const path = glyph.getPath(0, 0, UNITS)
  const d = closedPathData(path)
  if (!d) throw new Error(`empty path for ${ch}`)
  const box = path.getBoundingBox()
  return {
    d,
    codepoint: ch.codePointAt(0)!,
    bbox: {
      x: round(box.x1),
      y: round(box.y1),
      w: round(box.x2 - box.x1),
      h: round(box.y2 - box.y1),
    },
  }
}

function main() {
  const font = opentype.parse(readFileSync(FONT_PATH).buffer)
  const family = nameEn(font.names, 'fontFamily') || 'Noto Sans Symbols'
  const subfamily = nameEn(font.names, 'fontSubfamily') || 'Regular'
  const version = nameEn(font.names, 'version') || ''
  const license = nameEn(font.names, 'license')
  const licenseURL = nameEn(font.names, 'licenseURL') || 'http://scripts.sil.org/OFL'
  const copyright = nameEn(font.names, 'copyright')

  if (!/open font license/i.test(license)) {
    throw new Error(`refusing a font whose name-table licence is not OFL: ${license}`)
  }

  const rows = ZODIAC_SET.map(({ id, ch }) => {
    const glyph = pathData(font, ch)
    return `  ${JSON.stringify(id)}: ${JSON.stringify({ ...glyph, char: ch })},`
  })

  const body = `/**
 * Generated by scripts/build-talisman-zodiac.ts. Do not edit by hand.
 *
 * Font: ${family} ${subfamily}
 * Version: ${version}
 * Licence: SIL Open Font License, Version 1.1
 * Licence URL: ${licenseURL}
 * Copyright: ${copyright}
 *
 * Zodiac signs (U+2648–U+2653) traced from Noto Sans Symbols, OFL-1.1.
 * No commercial or unknown-licence dingbat font was used.
 *
 * Paths are closed contours for fill-rule="evenodd".
 */

export const TALISMAN_ZODIAC_FONT = ${JSON.stringify(`${family} ${subfamily}`)}
export const TALISMAN_ZODIAC_VERSION = ${JSON.stringify(version)}
export const TALISMAN_ZODIAC_LICENCE = 'SIL Open Font License, Version 1.1'
export const TALISMAN_ZODIAC_UNITS = ${UNITS}

export type TalismanZodiacPath = {
  d: string
  codepoint: number
  char: string
  bbox: { x: number; y: number; w: number; h: number }
}

export const TALISMAN_ZODIAC_IDS = [
  'aries',
  'taurus',
  'gemini',
  'cancer',
  'leo',
  'virgo',
  'libra',
  'scorpio',
  'sagittarius',
  'capricorn',
  'aquarius',
  'pisces',
] as const

export type TalismanZodiacId = (typeof TALISMAN_ZODIAC_IDS)[number]

export const TALISMAN_ZODIAC: Record<TalismanZodiacId, TalismanZodiacPath> = {
${rows.join('\n')}
}
`

  writeFileSync(OUT_PATH, body, 'utf8')
  console.log(`wrote ${OUT_PATH} (${ZODIAC_SET.length} signs, font ${family} ${subfamily})`)
}

main()
