/**
 * Convert every hanja the 부적 SVG can render into static SVG path data.
 *
 * Font: Noto Serif KR Regular (Korean subset of Noto Serif CJK / Source Han Serif).
 * Licence: SIL Open Font License 1.1 — commercial or unknown-licence seal fonts
 * are not allowed here.
 *
 * Contours are closed and meant to be filled with fill-rule="evenodd" so
 * counters (holes) stay open.
 *
 * Run: npx tsx scripts/build-talisman-glyphs.ts
 * Expects: third_party/fonts/NotoSerifKR-Regular.otf (gitignored).
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import opentype from 'opentype.js'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const FONT_PATH = resolve(ROOT, 'third_party/fonts/NotoSerifKR-Regular.otf')
const OUT_PATH = resolve(ROOT, 'lib/oracle/talisman/glyphs.generated.ts')

const UNITS = 1000

/** Centre 오행, 符膽, 천간, 지지, plus 空 for an untimed pillar. */
const GLYPH_SET = [
  '木',
  '火',
  '土',
  '金',
  '水',
  '財',
  '和',
  '合',
  '登',
  '科',
  '康',
  '寧',
  '鎭',
  '甲',
  '乙',
  '丙',
  '丁',
  '戊',
  '己',
  '庚',
  '辛',
  '壬',
  '癸',
  '子',
  '丑',
  '寅',
  '卯',
  '辰',
  '巳',
  '午',
  '未',
  '申',
  '酉',
  '戌',
  '亥',
  '空',
] as const

function nameEn(names: opentype.Font['names'], key: string): string {
  const table = names as unknown as Record<string, Record<string, Record<string, string>>>
  return table.windows?.[key]?.en ?? table.macintosh?.[key]?.en ?? ''
}

function round(n: number): number {
  return Math.round(n * 100) / 100
}

/** Close every contour. opentype.js toPathData() drops Z on CFF fonts. */
function closedPathData(path: opentype.Path): string {
  const parts: string[] = []
  let open = false
  for (const cmd of path.commands) {
    if (cmd.type === 'M') {
      if (open) parts.push('Z')
      parts.push(`M${round(cmd.x)} ${round(cmd.y)}`)
      open = true
    } else if (cmd.type === 'L') {
      parts.push(`L${round(cmd.x)} ${round(cmd.y)}`)
    } else if (cmd.type === 'C') {
      parts.push(
        `C${round(cmd.x1)} ${round(cmd.y1)} ${round(cmd.x2)} ${round(cmd.y2)} ${round(cmd.x)} ${round(cmd.y)}`,
      )
    } else if (cmd.type === 'Q') {
      parts.push(`Q${round(cmd.x1)} ${round(cmd.y1)} ${round(cmd.x)} ${round(cmd.y)}`)
    } else if (cmd.type === 'Z') {
      parts.push('Z')
      open = false
    }
  }
  if (open) parts.push('Z')
  return parts.join('')
}

function pathData(font: opentype.Font, ch: string) {
  const glyph = font.charToGlyph(ch)
  if (!glyph || glyph.index === 0 || glyph.name === '.notdef') {
    throw new Error(`Noto Serif KR Regular is missing ${ch} (U+${ch.codePointAt(0)!.toString(16).toUpperCase()})`)
  }
  const path = glyph.getPath(0, 0, UNITS)
  const d = closedPathData(path)
  if (!d) throw new Error(`empty path for ${ch}`)
  const box = path.getBoundingBox()
  const advance = Math.round((glyph.advanceWidth / font.unitsPerEm) * UNITS)
  return {
    d,
    advance,
    codepoint: ch.codePointAt(0)!,
    bbox: {
      x: round(box.x1),
      y: round(box.y1),
      w: round(box.x2 - box.x1),
      h: round(box.y2 - box.y1),
    },
  }
}

function main() {
  const font = opentype.parse(readFileSync(FONT_PATH).buffer)
  const family = nameEn(font.names, 'fontFamily') || 'Noto Serif KR'
  const subfamily = nameEn(font.names, 'fontSubfamily') || 'Regular'
  const version = nameEn(font.names, 'version') || 'Version 2.003'
  const license = nameEn(font.names, 'license')
  const licenseURL = nameEn(font.names, 'licenseURL') || 'http://scripts.sil.org/OFL'
  const copyright = nameEn(font.names, 'copyright')

  if (!/open font license/i.test(license)) {
    throw new Error(`refusing a font whose name-table licence is not OFL: ${license}`)
  }

  const rows = GLYPH_SET.map((ch) => {
    const glyph = pathData(font, ch)
    return `  ${JSON.stringify(ch)}: ${JSON.stringify(glyph)},`
  })

  const body = `/**
 * Generated by scripts/build-talisman-glyphs.ts. Do not edit by hand.
 *
 * Font: ${family} ${subfamily}
 * Version: ${version}
 * Licence: SIL Open Font License, Version 1.1
 * Licence URL: ${licenseURL}
 * Copyright: ${copyright}
 *
 * ${family} is the Korean region-specific subset of Noto Serif CJK
 * (Adobe Source Han Serif), OFL-1.1. No commercial or unknown-licence
 * calligraphy / seal font was used.
 *
 * Paths are closed contours for fill-rule="evenodd".
 */

export const TALISMAN_GLYPH_FONT = ${JSON.stringify(`${family} ${subfamily}`)}
export const TALISMAN_GLYPH_VERSION = ${JSON.stringify(version)}
export const TALISMAN_GLYPH_LICENCE = 'SIL Open Font License, Version 1.1'
export const TALISMAN_GLYPH_UNITS = ${UNITS}

export type TalismanGlyphPath = {
  d: string
  advance: number
  codepoint: number
  bbox: { x: number; y: number; w: number; h: number }
}

export const TALISMAN_GLYPHS: Record<string, TalismanGlyphPath> = {
${rows.join('\n')}
}
`

  writeFileSync(OUT_PATH, body, 'utf8')
  console.log(`wrote ${OUT_PATH} (${GLYPH_SET.length} glyphs, font ${family} ${subfamily})`)
}

main()
