import { NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase/server'
import { creditsForLeagueGenerate } from '@/lib/credits'
import { deductCreditsBalance } from '@/lib/credits-server'
import { generatePredictions, type ModelRunResult, type RoundInput } from '@/lib/league/orchestrator'
import { LEAGUE_GENERATE_RATE_RULE, tuningForViewer, type GenerateTuning } from '@/lib/league/access-policy'
import {
  authorizeRoundForViewer,
  enforceRateLimit,
  forbiddenResponse,
  resolveLeagueViewer,
  resolvePublicInstrumentRound,
  type LeagueViewer,
} from '@/lib/league/public-access'
import type { LeagueTier } from '@/lib/league/roster'
import { formatRosterBrand, lookupRosterEntry, rosterModelIdentifier } from '@/lib/league/roster'

/** Mirrors app/api/admin/league/generate/route.ts's budget — same fan-out, just streamed. */
export const maxDuration = 180

const VALID_TIERS: LeagueTier[] = ['premier', 'challenger', 'world', 'scout']

/**
 * AI Prediction League — LIVE generation stream. THE PAID LEAGUE PATH.
 *
 * POST /api/league/generate-stream
 * Body:
 *   { roundId }                  — re-run an existing round (public + admin)
 *   { instrument: 'AAPL' }       — today's ranked round for a curated
 *                                  instrument (public + admin)
 *   { round: { ... } }           — create an arbitrary round (ADMIN ONLY)
 * plus optional `tiers` / `concurrency` / `timeoutMs` / `maxCompletionTokens` /
 * `costCapUsd` (ADMIN ONLY — silently ignored for everyone else).
 *
 * THIS IS THE LIVE PATH ONLY. Ranked league instruments are pre-generated by
 * the cron (`app/api/cron/league/open`) and read back via the stored, cached,
 * FREE path (`GET /api/league/card`) — that default is unchanged. A caller has
 * to explicitly hit this endpoint to get a live run at all (see
 * `PredictionCard`'s `live` prop, which stays `false` unless a caller opts in).
 *
 * ORDER OF ENFORCEMENT (deliberate — everything that can reject must reject
 * before anything that can cost money):
 *   1. auth            -> 401. Any logged-in user; was admin-only.
 *   2. rate limit      -> 429, per user, before compute AND before charging,
 *                         so a throttled caller is never billed.
 *   3. target policy   -> 403/404. Non-admin: RANKED rounds on CURATED
 *                         instruments only, jurisdiction-allowed category
 *                         only, and NO arbitrary round creation (that is
 *                         on-demand search, which is not open yet).
 *   4. cost knobs      -> stripped for non-admin, so the fixed price buys a
 *                         fixed amount of work.
 *   5. credits         -> 402 on insufficient balance, BEFORE the stream opens
 *                         and before a single provider call. Admin skips the
 *                         charge (pre-existing `deductCreditsBalance` bypass).
 *
 * WIRE FORMAT: newline-delimited JSON, one JSON object per line, EXACTLY the
 * existing convention in `app/api/ai-compare/route.ts` — not a new transport.
 *   {"type":"round","round_id":"...","created":true,"roster_size":21} — once, first
 *   {"type":"model", ...CardModelPrediction-shaped fields, "status":"ok"}
 *                                                               — one per model,
 *                                                                 in arrival order
 *   {"type":"done","round_id":"...","total_cost_usd":0.12,"capped":false}
 *   {"type":"error","error":"..."}                             — on failure
 *
 * DB-IS-TRUTH CONTRACT: each "model" line is emitted from
 * `generatePredictions`'s `onModelResult` hook, which fires strictly AFTER
 * that model's `model_predictions` row is written (see orchestrator.ts). This
 * route never buffers or invents model state — it only narrates writes that
 * already happened. If this connection drops mid-stream, every model that had
 * already answered is already in the DB and `GET /api/league/card` will
 * return it; nothing is lost, and nothing here needs its own persistence.
 *
 * Reuses `generatePredictions` UNCHANGED (concurrency cap, kill-switch,
 * abstain/timeout handling, retry) — this route adds zero orchestration logic
 * of its own, only two optional callback taps.
 */
export async function POST(req: Request) {
  let body: Record<string, unknown>
  try {
    body = (await req.json()) as Record<string, unknown>
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  const auth = await resolveLeagueViewer(req, body)
  if (!auth.ok) return auth.response
  const { viewer } = auth

  const limited = enforceRateLimit(viewer, 'league_generate', LEAGUE_GENERATE_RATE_RULE)
  if (limited) return limited

  const target = await resolveTarget(viewer, body)
  if ('response' in target) return target.response

  const tuning = tuningForViewer(parseTuning(body), viewer.isAdmin)

  const cost = creditsForLeagueGenerate()
  const deduct = await deductCreditsBalance(supabaseAdmin, viewer.userId, cost, 'league_generate')
  if (!deduct.ok) {
    const insufficient = deduct.reason === 'insufficient'
    return NextResponse.json(
      {
        error: insufficient ? 'Insufficient credits' : 'Could not update credits',
        balance: deduct.balance,
        required: cost,
      },
      { status: insufficient ? 402 : 500 }
    )
  }

  const enc = new TextEncoder()

  const stream = new ReadableStream({
    async start(controller) {
      const writeJson = (obj: unknown) => {
        controller.enqueue(enc.encode(`${JSON.stringify(obj)}\n`))
      }

      try {
        const result = await generatePredictions({
          round: target.round,
          ...tuning,
          userId: viewer.userId,
          onRoundResolved: (round) => {
            writeJson({ type: 'round', round_id: round.id, created: round.created, roster_size: round.rosterSize })
          },
          onModelResult: (result) => {
            writeJson({ type: 'model', ...toWireModel(result) })
          },
        })

        writeJson({
          type: 'done',
          round_id: result.round_id,
          total_cost_usd: result.total_cost_usd,
          capped: result.capped,
        })
      } catch (e: unknown) {
        const msg = e instanceof Error ? e.message : 'Unknown error'
        writeJson({ type: 'error', error: msg })
      } finally {
        controller.close()
      }
    },
  })

  return new Response(stream, {
    headers: {
      'Content-Type': 'application/x-ndjson; charset=utf-8',
      'Cache-Control': 'no-store',
    },
  })
}

/**
 * Resolves WHAT this caller is allowed to generate.
 *
 * The public surface is deliberately narrow: a public caller can only re-run a
 * round that the cron already opened for a curated instrument. They cannot
 * name a proposition, a category, an instrument, or a resolution rule — which
 * is what keeps this endpoint from being an open, arbitrary-prompt, arbitrary-
 * cost LLM fan-out behind a fixed 7-credit price, and what keeps the
 * jurisdiction matrix meaningful (you cannot invent a round in a category you
 * are not allowed to see).
 */
async function resolveTarget(
  viewer: LeagueViewer,
  body: Record<string, unknown>
): Promise<{ round: RoundInput } | { response: NextResponse }> {
  const roundId = typeof body.roundId === 'string' ? body.roundId.trim() : ''
  const instrument = typeof body.instrument === 'string' ? body.instrument.trim() : ''

  if (roundId) {
    const access = await authorizeRoundForViewer(viewer, roundId)
    if (!access.ok) return { response: access.response }
    return { round: { roundId: access.roundId } }
  }

  if (instrument) {
    const access = await resolvePublicInstrumentRound(viewer, instrument)
    if (!access.ok) return { response: access.response }
    return { round: { roundId: access.roundId } }
  }

  const arbitrary = buildArbitraryRoundInput(body)
  if (arbitrary) {
    // Creating a round from a caller-supplied proposition IS on-demand
    // generation. Admin-only until that product piece ships.
    if (!viewer.isAdmin) return { response: forbiddenResponse('not_public') }
    return { round: arbitrary }
  }

  return {
    response: NextResponse.json(
      { error: 'Provide { roundId } or { instrument }', code: 'missing_target' },
      { status: 400 }
    ),
  }
}

/**
 * A superset of the requested `{model_id, brand, camp, league_tier, direction,
 * probability, status}` shape: also includes `reasoning_snippet`/`cost_usd`/
 * `is_correct`/`predicted_at` so the client receives an object that is
 * directly a valid `CardModelPrediction` (see card-types.ts) and can merge it
 * straight into `CardData.models` with no lossy re-shaping. `is_correct` is
 * always null here — grading only happens after resolution, never during a
 * live run. `predicted_at` is this line's emit time (a close approximation;
 * the DB row's own timestamp is the actual source of truth and is what a
 * later `GET /api/league/card` returns).
 */
function toWireModel(result: ModelRunResult) {
  const roster = lookupRosterEntry(result.model_id)
  return {
    prediction_id: null as string | null,
    model_id: result.model_id,
    brand: roster ? formatRosterBrand(roster) : result.brand,
    model_identifier: roster ? rosterModelIdentifier(roster) : result.model_id,
    camp: result.camp,
    league_tier: result.tier,
    direction: result.direction,
    probability: result.probability,
    reasoning_snippet: result.reasoning_snippet,
    is_correct: null as boolean | null,
    cost_usd: result.cost_usd,
    predicted_at: new Date().toISOString(),
    status: result.status,
  }
}

/** Admin-only branch: a fully caller-specified round. Same shape as `POST /api/admin/league/generate`. */
function buildArbitraryRoundInput(body: Record<string, unknown>): RoundInput | null {
  const r = body.round
  if (!r || typeof r !== 'object') return null
  const o = r as Record<string, unknown>
  const required = ['proposition_text', 'category', 'instrument', 'horizon', 'resolution_rule', 'resolves_at']
  if (!required.every((k) => typeof o[k] === 'string' && (o[k] as string).length > 0)) return null
  return {
    proposition_text: o.proposition_text as string,
    category: o.category as string,
    instrument: o.instrument as string,
    horizon: o.horizon as string,
    resolution_rule: o.resolution_rule as string,
    resolves_at: o.resolves_at as string,
    item_type: o.item_type === 'on_demand' ? 'on_demand' : 'ranked',
    season_id: typeof o.season_id === 'string' ? o.season_id : null,
    cache_key: typeof o.cache_key === 'string' ? o.cache_key : null,
  }
}

function parseTuning(body: Record<string, unknown>): GenerateTuning {
  return {
    tiers: parseTiers(body.tiers),
    concurrency: numOrUndefined(body.concurrency),
    timeoutMs: numOrUndefined(body.timeoutMs),
    maxCompletionTokens: numOrUndefined(body.maxCompletionTokens),
    costCapUsd: numOrUndefined(body.costCapUsd),
  }
}

function parseTiers(raw: unknown): LeagueTier[] | undefined {
  if (!Array.isArray(raw)) return undefined
  const tiers = raw.filter((t): t is LeagueTier => VALID_TIERS.includes(t as LeagueTier))
  return tiers.length ? tiers : undefined
}

function numOrUndefined(raw: unknown): number | undefined {
  const n = Number(raw)
  return Number.isFinite(n) && n > 0 ? n : undefined
}
