import { NextResponse } from 'next/server'
import { requireAdmin } from '@/lib/admin/require-admin'
import { createSupabaseRouteAuthClient } from '@/lib/supabase/route-auth'
import { supabaseAdmin } from '@/lib/supabase/server'
import { generatePredictions, type ModelRunResult, type RoundInput } from '@/lib/league/orchestrator'
import type { LeagueTier } from '@/lib/league/roster'

/** Mirrors app/api/admin/league/generate/route.ts's budget — same fan-out, just streamed. */
export const maxDuration = 180

const VALID_TIERS: LeagueTier[] = ['premier', 'challenger', 'world', 'scout']

/**
 * AI Prediction League — LIVE generation stream.
 *
 * POST /api/league/generate-stream
 * Body: same shape as `POST /api/admin/league/generate` — either
 * `{ roundId }` (re-run/continue an existing round) or
 * `{ round: { proposition_text, category, instrument, horizon,
 *             resolution_rule, resolves_at, item_type? } }` (create one),
 * plus optional `tiers` / `concurrency` / `timeoutMs` / `maxCompletionTokens` /
 * `costCapUsd`.
 *
 * THIS IS THE ON-DEMAND / FRESH-ROUND PATH ONLY. Ranked league instruments are
 * pre-generated by the cron (`app/api/cron/league/open`) and read back via the
 * stored, cached path (`GET /api/league/card`) — that default is unchanged by
 * this route. Nothing here makes the card default to live generation; a
 * caller has to explicitly hit this endpoint to get a live run at all (see
 * `PredictionCard`'s `live` prop, which stays `false` unless a caller opts in).
 *
 * WIRE FORMAT: newline-delimited JSON, one JSON object per line, EXACTLY the
 * existing convention in `app/api/ai-compare/route.ts` — not a new transport.
 *   {"type":"round","round_id":"...","created":true,"roster_size":21} — once, first
 *   {"type":"model", ...CardModelPrediction-shaped fields, "status":"ok"}
 *                                                               — one per model,
 *                                                                 in arrival order
 *   {"type":"done","round_id":"...","total_cost_usd":0.12,"capped":false}
 *   {"type":"error","error":"..."}                             — on failure
 *
 * DB-IS-TRUTH CONTRACT: each "model" line is emitted from
 * `generatePredictions`'s `onModelResult` hook, which fires strictly AFTER
 * that model's `model_predictions` row is written (see orchestrator.ts). This
 * route never buffers or invents model state — it only narrates writes that
 * already happened. If this connection drops mid-stream, every model that had
 * already answered is already in the DB and `GET /api/league/card` will
 * return it; nothing is lost, and nothing here needs its own persistence.
 *
 * Reuses `generatePredictions` UNCHANGED (concurrency cap, kill-switch,
 * abstain/timeout handling, retry) — this route adds zero orchestration logic
 * of its own, only two optional callback taps.
 *
 * Admin-gated, same as every other league route (`requireAdmin`).
 */
export async function POST(req: Request) {
  const forbidden = await requireAdmin(req)
  if (forbidden) return forbidden

  let body: Record<string, unknown>
  try {
    body = (await req.json()) as Record<string, unknown>
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  const roundInput = buildRoundInput(body)
  if (!roundInput) {
    return NextResponse.json(
      {
        error:
          'Provide either { roundId } or { round: { proposition_text, category, instrument, horizon, resolution_rule, resolves_at } }',
      },
      { status: 400 }
    )
  }

  const tiers = parseTiers(body.tiers)
  const concurrency = numOrUndefined(body.concurrency)
  const timeoutMs = numOrUndefined(body.timeoutMs)
  const maxCompletionTokens = numOrUndefined(body.maxCompletionTokens)
  const costCapUsd = numOrUndefined(body.costCapUsd)
  const userId = await getAdminUserId(req)

  const enc = new TextEncoder()

  const stream = new ReadableStream({
    async start(controller) {
      const writeJson = (obj: unknown) => {
        controller.enqueue(enc.encode(`${JSON.stringify(obj)}\n`))
      }

      try {
        const result = await generatePredictions({
          round: roundInput,
          tiers,
          concurrency,
          timeoutMs,
          maxCompletionTokens,
          costCapUsd,
          userId,
          onRoundResolved: (round) => {
            writeJson({ type: 'round', round_id: round.id, created: round.created, roster_size: round.rosterSize })
          },
          onModelResult: (result) => {
            writeJson({ type: 'model', ...toWireModel(result) })
          },
        })

        writeJson({
          type: 'done',
          round_id: result.round_id,
          total_cost_usd: result.total_cost_usd,
          capped: result.capped,
        })
      } catch (e: unknown) {
        const msg = e instanceof Error ? e.message : 'Unknown error'
        writeJson({ type: 'error', error: msg })
      } finally {
        controller.close()
      }
    },
  })

  return new Response(stream, {
    headers: {
      'Content-Type': 'application/x-ndjson; charset=utf-8',
      'Cache-Control': 'no-store',
    },
  })
}

/**
 * A superset of the requested `{model_id, brand, camp, league_tier, direction,
 * probability, status}` shape: also includes `reasoning_snippet`/`cost_usd`/
 * `is_correct`/`predicted_at` so the client receives an object that is
 * directly a valid `CardModelPrediction` (see card-types.ts) and can merge it
 * straight into `CardData.models` with no lossy re-shaping. `is_correct` is
 * always null here — grading only happens after resolution, never during a
 * live run. `predicted_at` is this line's emit time (a close approximation;
 * the DB row's own timestamp is the actual source of truth and is what a
 * later `GET /api/league/card` returns).
 */
function toWireModel(result: ModelRunResult) {
  return {
    model_id: result.model_id,
    brand: result.brand,
    camp: result.camp,
    league_tier: result.tier,
    direction: result.direction,
    probability: result.probability,
    reasoning_snippet: result.reasoning_snippet,
    is_correct: null as boolean | null,
    cost_usd: result.cost_usd,
    predicted_at: new Date().toISOString(),
    status: result.status,
  }
}

function buildRoundInput(body: Record<string, unknown>): RoundInput | null {
  if (typeof body.roundId === 'string' && body.roundId.trim()) {
    return { roundId: body.roundId.trim() }
  }
  const r = body.round
  if (r && typeof r === 'object') {
    const o = r as Record<string, unknown>
    const required = ['proposition_text', 'category', 'instrument', 'horizon', 'resolution_rule', 'resolves_at']
    if (required.every((k) => typeof o[k] === 'string' && (o[k] as string).length > 0)) {
      const itemType = o.item_type === 'on_demand' ? 'on_demand' : 'ranked'
      return {
        proposition_text: o.proposition_text as string,
        category: o.category as string,
        instrument: o.instrument as string,
        horizon: o.horizon as string,
        resolution_rule: o.resolution_rule as string,
        resolves_at: o.resolves_at as string,
        item_type: itemType,
        season_id: typeof o.season_id === 'string' ? o.season_id : null,
        cache_key: typeof o.cache_key === 'string' ? o.cache_key : null,
      }
    }
  }
  return null
}

function parseTiers(raw: unknown): LeagueTier[] | undefined {
  if (!Array.isArray(raw)) return undefined
  const tiers = raw.filter((t): t is LeagueTier => VALID_TIERS.includes(t as LeagueTier))
  return tiers.length ? tiers : undefined
}

function numOrUndefined(raw: unknown): number | undefined {
  const n = Number(raw)
  return Number.isFinite(n) && n > 0 ? n : undefined
}

/** Resolve the admin's user id (for optional core-model BYOK reads). Mirrors app/api/admin/league/generate/route.ts. */
async function getAdminUserId(req: Request): Promise<string | null> {
  const authHeader = req.headers.get('authorization')
  const bearer = authHeader?.startsWith('Bearer ') ? authHeader.slice(7).trim() : undefined
  let jwt = bearer
  if (!jwt) {
    const authClient = await createSupabaseRouteAuthClient(req)
    const {
      data: { session },
    } = await authClient.auth.getSession()
    jwt = session?.access_token
  }
  if (!jwt) return null
  const { data, error } = await supabaseAdmin.auth.getUser(jwt)
  if (error || !data.user?.id) return null
  return data.user.id
}
